/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderIndexRouteImport } from './routes/order/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DiyIndexRouteImport } from './routes/diy/index'
import { Route as DeviceIndexRouteImport } from './routes/device/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users.$userId'

const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiyIndexRoute = DiyIndexRouteImport.update({
  id: '/diy/',
  path: '/diy/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceIndexRoute = DeviceIndexRouteImport.update({
  id: '/device/',
  path: '/device/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/device/': typeof DeviceIndexRoute
  '/diy/': typeof DiyIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/order/': typeof OrderIndexRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/app': typeof AppIndexRoute
  '/device': typeof DeviceIndexRoute
  '/diy': typeof DiyIndexRoute
  '/docs': typeof DocsIndexRoute
  '/order': typeof OrderIndexRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/device/': typeof DeviceIndexRoute
  '/diy/': typeof DiyIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/order/': typeof OrderIndexRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/api/users'
    | '/app/'
    | '/device/'
    | '/diy/'
    | '/docs/'
    | '/order/'
    | '/api/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/api/users'
    | '/app'
    | '/device'
    | '/diy'
    | '/docs'
    | '/order'
    | '/api/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/customScript.js'
    | '/api/users'
    | '/app/'
    | '/device/'
    | '/diy/'
    | '/docs/'
    | '/order/'
    | '/api/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  DeviceIndexRoute: typeof DeviceIndexRoute
  DiyIndexRoute: typeof DiyIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  OrderIndexRoute: typeof OrderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order/'
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diy/': {
      id: '/diy/'
      path: '/diy'
      fullPath: '/diy/'
      preLoaderRoute: typeof DiyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/': {
      id: '/device/'
      path: '/device'
      fullPath: '/device/'
      preLoaderRoute: typeof DeviceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
  }
}

interface ApiUsersRouteChildren {
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  DeviceIndexRoute: DeviceIndexRoute,
  DiyIndexRoute: DiyIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  OrderIndexRoute: OrderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
