/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as OrderIndexRouteImport } from './routes/order/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ImprintIndexRouteImport } from './routes/imprint/index'
import { Route as FeedbackIndexRouteImport } from './routes/feedback/index'
import { Route as DownloadIndexRouteImport } from './routes/download/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DiyIndexRouteImport } from './routes/diy/index'
import { Route as DeviceIndexRouteImport } from './routes/device/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthMobileCallbackRouteImport } from './routes/auth/mobile-callback'
import { Route as AuthExtensionCallbackRouteImport } from './routes/auth/extension-callback'
import { Route as AppSplatRouteImport } from './routes/app/$'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiBetaRequestRouteImport } from './routes/api/beta-request'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as ApiSyncWipeSessionsRouteImport } from './routes/api/sync/wipe-sessions'
import { Route as ApiImportArticleRouteImport } from './routes/api/import/article'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintIndexRoute = ImprintIndexRouteImport.update({
  id: '/imprint/',
  path: '/imprint/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackIndexRoute = FeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadIndexRoute = DownloadIndexRouteImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiyIndexRoute = DiyIndexRouteImport.update({
  id: '/diy/',
  path: '/diy/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceIndexRoute = DeviceIndexRouteImport.update({
  id: '/device/',
  path: '/device/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMobileCallbackRoute = AuthMobileCallbackRouteImport.update({
  id: '/auth/mobile-callback',
  path: '/auth/mobile-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthExtensionCallbackRoute = AuthExtensionCallbackRouteImport.update({
  id: '/auth/extension-callback',
  path: '/auth/extension-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/app/$',
  path: '/app/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetaRequestRoute = ApiBetaRequestRouteImport.update({
  id: '/api/beta-request',
  path: '/api/beta-request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiSyncWipeSessionsRoute = ApiSyncWipeSessionsRouteImport.update({
  id: '/wipe-sessions',
  path: '/wipe-sessions',
  getParentRoute: () => ApiSyncRoute,
} as any)
const ApiImportArticleRoute = ApiImportArticleRouteImport.update({
  id: '/api/import/article',
  path: '/api/import/article',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/beta-request': typeof ApiBetaRequestRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/sync': typeof ApiSyncRouteWithChildren
  '/app/$': typeof AppSplatRoute
  '/auth/extension-callback': typeof AuthExtensionCallbackRoute
  '/auth/mobile-callback': typeof AuthMobileCallbackRoute
  '/app/': typeof AppIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/device/': typeof DeviceIndexRoute
  '/diy/': typeof DiyIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/download/': typeof DownloadIndexRoute
  '/feedback/': typeof FeedbackIndexRoute
  '/imprint/': typeof ImprintIndexRoute
  '/login/': typeof LoginIndexRoute
  '/order/': typeof OrderIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/import/article': typeof ApiImportArticleRoute
  '/api/sync/wipe-sessions': typeof ApiSyncWipeSessionsRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/beta-request': typeof ApiBetaRequestRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/sync': typeof ApiSyncRouteWithChildren
  '/app/$': typeof AppSplatRoute
  '/auth/extension-callback': typeof AuthExtensionCallbackRoute
  '/auth/mobile-callback': typeof AuthMobileCallbackRoute
  '/app': typeof AppIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/device': typeof DeviceIndexRoute
  '/diy': typeof DiyIndexRoute
  '/docs': typeof DocsIndexRoute
  '/download': typeof DownloadIndexRoute
  '/feedback': typeof FeedbackIndexRoute
  '/imprint': typeof ImprintIndexRoute
  '/login': typeof LoginIndexRoute
  '/order': typeof OrderIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/terms': typeof TermsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/import/article': typeof ApiImportArticleRoute
  '/api/sync/wipe-sessions': typeof ApiSyncWipeSessionsRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/beta-request': typeof ApiBetaRequestRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/sync': typeof ApiSyncRouteWithChildren
  '/app/$': typeof AppSplatRoute
  '/auth/extension-callback': typeof AuthExtensionCallbackRoute
  '/auth/mobile-callback': typeof AuthMobileCallbackRoute
  '/app/': typeof AppIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/device/': typeof DeviceIndexRoute
  '/diy/': typeof DiyIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/download/': typeof DownloadIndexRoute
  '/feedback/': typeof FeedbackIndexRoute
  '/imprint/': typeof ImprintIndexRoute
  '/login/': typeof LoginIndexRoute
  '/order/': typeof OrderIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/import/article': typeof ApiImportArticleRoute
  '/api/sync/wipe-sessions': typeof ApiSyncWipeSessionsRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/beta-request'
    | '/api/feedback'
    | '/api/sync'
    | '/app/$'
    | '/auth/extension-callback'
    | '/auth/mobile-callback'
    | '/app/'
    | '/changelog/'
    | '/device/'
    | '/diy/'
    | '/docs/'
    | '/download/'
    | '/feedback/'
    | '/imprint/'
    | '/login/'
    | '/order/'
    | '/privacy/'
    | '/terms/'
    | '/api/auth/$'
    | '/api/import/article'
    | '/api/sync/wipe-sessions'
    | '/account/'
    | '/admin/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/beta-request'
    | '/api/feedback'
    | '/api/sync'
    | '/app/$'
    | '/auth/extension-callback'
    | '/auth/mobile-callback'
    | '/app'
    | '/changelog'
    | '/device'
    | '/diy'
    | '/docs'
    | '/download'
    | '/feedback'
    | '/imprint'
    | '/login'
    | '/order'
    | '/privacy'
    | '/terms'
    | '/api/auth/$'
    | '/api/import/article'
    | '/api/sync/wipe-sessions'
    | '/account'
    | '/admin'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/customScript.js'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/beta-request'
    | '/api/feedback'
    | '/api/sync'
    | '/app/$'
    | '/auth/extension-callback'
    | '/auth/mobile-callback'
    | '/app/'
    | '/changelog/'
    | '/device/'
    | '/diy/'
    | '/docs/'
    | '/download/'
    | '/feedback/'
    | '/imprint/'
    | '/login/'
    | '/order/'
    | '/privacy/'
    | '/terms/'
    | '/api/auth/$'
    | '/api/import/article'
    | '/api/sync/wipe-sessions'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
    | '/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiBetaRequestRoute: typeof ApiBetaRequestRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiSyncRoute: typeof ApiSyncRouteWithChildren
  AppSplatRoute: typeof AppSplatRoute
  AuthExtensionCallbackRoute: typeof AuthExtensionCallbackRoute
  AuthMobileCallbackRoute: typeof AuthMobileCallbackRoute
  AppIndexRoute: typeof AppIndexRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  DeviceIndexRoute: typeof DeviceIndexRoute
  DiyIndexRoute: typeof DiyIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DownloadIndexRoute: typeof DownloadIndexRoute
  FeedbackIndexRoute: typeof FeedbackIndexRoute
  ImprintIndexRoute: typeof ImprintIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OrderIndexRoute: typeof OrderIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiImportArticleRoute: typeof ApiImportArticleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order/'
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint/': {
      id: '/imprint/'
      path: '/imprint'
      fullPath: '/imprint/'
      preLoaderRoute: typeof ImprintIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/': {
      id: '/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof FeedbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/': {
      id: '/download/'
      path: '/download'
      fullPath: '/download/'
      preLoaderRoute: typeof DownloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diy/': {
      id: '/diy/'
      path: '/diy'
      fullPath: '/diy/'
      preLoaderRoute: typeof DiyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/': {
      id: '/device/'
      path: '/device'
      fullPath: '/device/'
      preLoaderRoute: typeof DeviceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mobile-callback': {
      id: '/auth/mobile-callback'
      path: '/auth/mobile-callback'
      fullPath: '/auth/mobile-callback'
      preLoaderRoute: typeof AuthMobileCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/extension-callback': {
      id: '/auth/extension-callback'
      path: '/auth/extension-callback'
      fullPath: '/auth/extension-callback'
      preLoaderRoute: typeof AuthExtensionCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$': {
      id: '/app/$'
      path: '/app/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beta-request': {
      id: '/api/beta-request'
      path: '/api/beta-request'
      fullPath: '/api/beta-request'
      preLoaderRoute: typeof ApiBetaRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/sync/wipe-sessions': {
      id: '/api/sync/wipe-sessions'
      path: '/wipe-sessions'
      fullPath: '/api/sync/wipe-sessions'
      preLoaderRoute: typeof ApiSyncWipeSessionsRouteImport
      parentRoute: typeof ApiSyncRoute
    }
    '/api/import/article': {
      id: '/api/import/article'
      path: '/api/import/article'
      fullPath: '/api/import/article'
      preLoaderRoute: typeof ApiImportArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiSyncRouteChildren {
  ApiSyncWipeSessionsRoute: typeof ApiSyncWipeSessionsRoute
}

const ApiSyncRouteChildren: ApiSyncRouteChildren = {
  ApiSyncWipeSessionsRoute: ApiSyncWipeSessionsRoute,
}

const ApiSyncRouteWithChildren =
  ApiSyncRoute._addFileChildren(ApiSyncRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiBetaRequestRoute: ApiBetaRequestRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiSyncRoute: ApiSyncRouteWithChildren,
  AppSplatRoute: AppSplatRoute,
  AuthExtensionCallbackRoute: AuthExtensionCallbackRoute,
  AuthMobileCallbackRoute: AuthMobileCallbackRoute,
  AppIndexRoute: AppIndexRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  DeviceIndexRoute: DeviceIndexRoute,
  DiyIndexRoute: DiyIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  DownloadIndexRoute: DownloadIndexRoute,
  FeedbackIndexRoute: FeedbackIndexRoute,
  ImprintIndexRoute: ImprintIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  OrderIndexRoute: OrderIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiImportArticleRoute: ApiImportArticleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
