/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as OrderIndexRouteImport } from './routes/order/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ImprintIndexRouteImport } from './routes/imprint/index'
import { Route as DownloadIndexRouteImport } from './routes/download/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DiyIndexRouteImport } from './routes/diy/index'
import { Route as DeviceIndexRouteImport } from './routes/device/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSplatRouteImport } from './routes/app/$'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users.$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintIndexRoute = ImprintIndexRouteImport.update({
  id: '/imprint/',
  path: '/imprint/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadIndexRoute = DownloadIndexRouteImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiyIndexRoute = DiyIndexRouteImport.update({
  id: '/diy/',
  path: '/diy/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceIndexRoute = DeviceIndexRouteImport.update({
  id: '/device/',
  path: '/device/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/app/$',
  path: '/app/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/app/$': typeof AppSplatRoute
  '/app/': typeof AppIndexRoute
  '/device/': typeof DeviceIndexRoute
  '/diy/': typeof DiyIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/download/': typeof DownloadIndexRoute
  '/imprint/': typeof ImprintIndexRoute
  '/login/': typeof LoginIndexRoute
  '/order/': typeof OrderIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/app/$': typeof AppSplatRoute
  '/app': typeof AppIndexRoute
  '/device': typeof DeviceIndexRoute
  '/diy': typeof DiyIndexRoute
  '/docs': typeof DocsIndexRoute
  '/download': typeof DownloadIndexRoute
  '/imprint': typeof ImprintIndexRoute
  '/login': typeof LoginIndexRoute
  '/order': typeof OrderIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/terms': typeof TermsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/app/$': typeof AppSplatRoute
  '/app/': typeof AppIndexRoute
  '/device/': typeof DeviceIndexRoute
  '/diy/': typeof DiyIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/download/': typeof DownloadIndexRoute
  '/imprint/': typeof ImprintIndexRoute
  '/login/': typeof LoginIndexRoute
  '/order/': typeof OrderIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/sync'
    | '/api/users'
    | '/app/$'
    | '/app/'
    | '/device/'
    | '/diy/'
    | '/docs/'
    | '/download/'
    | '/imprint/'
    | '/login/'
    | '/order/'
    | '/privacy/'
    | '/terms/'
    | '/api/auth/$'
    | '/api/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/sync'
    | '/api/users'
    | '/app/$'
    | '/app'
    | '/device'
    | '/diy'
    | '/docs'
    | '/download'
    | '/imprint'
    | '/login'
    | '/order'
    | '/privacy'
    | '/terms'
    | '/api/auth/$'
    | '/api/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/customScript.js'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/sync'
    | '/api/users'
    | '/app/$'
    | '/app/'
    | '/device/'
    | '/diy/'
    | '/docs/'
    | '/download/'
    | '/imprint/'
    | '/login/'
    | '/order/'
    | '/privacy/'
    | '/terms/'
    | '/api/auth/$'
    | '/api/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  AppSplatRoute: typeof AppSplatRoute
  AppIndexRoute: typeof AppIndexRoute
  DeviceIndexRoute: typeof DeviceIndexRoute
  DiyIndexRoute: typeof DiyIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DownloadIndexRoute: typeof DownloadIndexRoute
  ImprintIndexRoute: typeof ImprintIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OrderIndexRoute: typeof OrderIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order/'
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint/': {
      id: '/imprint/'
      path: '/imprint'
      fullPath: '/imprint/'
      preLoaderRoute: typeof ImprintIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/': {
      id: '/download/'
      path: '/download'
      fullPath: '/download/'
      preLoaderRoute: typeof DownloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diy/': {
      id: '/diy/'
      path: '/diy'
      fullPath: '/diy/'
      preLoaderRoute: typeof DiyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/': {
      id: '/device/'
      path: '/device'
      fullPath: '/device/'
      preLoaderRoute: typeof DeviceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$': {
      id: '/app/$'
      path: '/app/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiUsersRouteChildren {
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  AppSplatRoute: AppSplatRoute,
  AppIndexRoute: AppIndexRoute,
  DeviceIndexRoute: DeviceIndexRoute,
  DiyIndexRoute: DiyIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  DownloadIndexRoute: DownloadIndexRoute,
  ImprintIndexRoute: ImprintIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  OrderIndexRoute: OrderIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
