export type ChangelogTag = "App" | "ESP32" | "Website";

export type ChangelogEntry = {
	date: string;
	title: string;
	tags: ChangelogTag[];
	changes: string[];
};

export const changelog: ChangelogEntry[] = [
	{
		date: "2026-06-08",
		title: "Library Layout Memory and Save Warnings",
		tags: ["App"],
		changes: [
			"The library now remembers your chosen layout (grid or list) and sort order between sessions",
			"If your reading progress can't be saved on your device, the app now warns you instead of failing silently",
			"New Settings → Privacy toggle to opt out of anonymous diagnostics (on by default, no account or personal data)",
		],
	},
	{
		date: "2026-06-07",
		title: "Large Book Imports and Cover Fixes",
		tags: ["App"],
		changes: [
			"Large EPUBs (over 50 MB) now import reliably instead of freezing or crashing the app",
			"Very large books are kept on the device that imported them and clearly marked as local only, since they're too big to sync to the cloud",
			"Book cover thumbnails now load for many more EPUBs, including files that previously showed a blank placeholder",
		],
	},
	{
		date: "2026-06-02",
		title: "Reader Links and Resume Reliability",
		tags: ["App"],
		changes: [
			"Hyperlinks in imported articles and EPUBs are now shown and tappable, opening in your browser",
			"Plain URLs written in any book are clickable too",
			"Your reading position is restored more reliably after closing or backgrounding the app",
		],
	},
	{
		date: "2026-05-29",
		title: "RSVP Wake Lock and Sync Fixes",
		tags: ["App"],
		changes: [
			"The screen now stays awake while you're reading in RSVP mode",
			"Refreshed app icon and splash screens, including a themed monochrome launcher icon",
			"Logged-out users no longer hit sync errors — server calls are skipped when sync is off",
			"More reliable chapter auto-advance and back-button behavior in serials",
		],
	},
	{
		date: "2026-05-23",
		title: "Redesign, Live Sync, and rsvpnano Firmware",
		tags: ["App", "ESP32"],
		changes: [
			"Refreshed app and reader design",
			"Live bi-directional position sync between the app and your device while you read",
			"More reliable position sync across devices and font sizes (positions are now tracked by word, not byte offset)",
			"rsvpnano firmware integration with an improved BLE transfer pipeline",
			"Improved BLE settings screen with clearer device status and controls",
			"More accurate reading session tracking and a fix for the WPM trend chart",
			"Faster and smoother chapter loading in long serials",
			"Various reader fixes around taps, drag scrubbing, and font sizing",
		],
	},
	{
		date: "2026-05-08",
		title: "Play Store Launch",
		tags: ["App"],
		changes: [
			"First public Play Store release",
			"Glossary marker no longer gets stranded at the end of a line while its term wraps to the next",
			'Glossary terms with surrounding punctuation or quotes (e.g. "Problem", Harmony.) are now matched and marked',
			'Adding a glossary entry from a selection like "pause." automatically strips surrounding punctuation',
		],
	},
	{
		date: "2026-05-03",
		title: "Stats Polish",
		tags: ["App"],
		changes: [
			"Browse and delete individual reading sessions from the stats page and book detail",
			"Small tweaks to the reading-speed reference line and top-books rank numerals",
		],
	},
	{
		date: "2026-05-01",
		title: "Reading Statistics",
		tags: ["App", "Website"],
		changes: [
			"New reading stats page in the library with totals, streak heatmap, top books, and reading personality",
			"Per-book stats card on the book detail page: total time, sessions, last read, and a speed sparkline",
			"Reading speed trends split into three series: RSVP target, RSVP delivered, and natural scroll/page reading, with a 250 WPM reference line",
			"Reading sessions now sync across your devices like the rest of your data",
			"Per-resource sync toggles in Sync settings so you can opt out of syncing highlights, glossary, or reading sessions",
			"Danger zone in Sync settings to bulk-delete highlights, glossary, reading stats, your library, or everything",
			"Reorganised the Settings page so related items are grouped together",
			"Admin page on the website rebuilt with better filtering and bulk actions",
		],
	},
	{
		date: "2026-04-30",
		title: "Feedback, Error Tracking, and Reader Polish",
		tags: ["App", "Website"],
		changes: [
			"You can now change the color of the focal letter",
			"Added a public feedback page and API endpoint",
			"Improved SEO and sitemap routing",
			"Integrated GlitchTip error tracking (browser + server)",
			"You can now export highlights from the settings",
			"Keyboard and mouse controls for the web reader",
			"Markdown (.md) import support",
			"Improved sync behavior and web novel scraping reliability",
		],
	},
	{
		date: "2026-04-29",
		title: "Web Novels",
		tags: ["App"],
		changes: [
			"Find and read serials from AO3, ScribbleHub, Royal Road, and Wuxiaworld right inside the app",
			"New Web Novels section on the Explore tab with a search across every provider at once",
			"Tap a result for a preview, then add the whole series to your library in one go",
			"Series get their own card in the library with a chapter count badge",
			"Open a series to see the full chapter list and jump back into where you left off",
			"Chapters download lazily when you open them, so adding a 500-chapter series is instant",
			"Finish a chapter and the reader auto-advances to the next one",
			"Re-open a series and it quietly checks for new chapters in the background",
			"You can also paste a series or chapter URL and it figures out the rest",
			"Switch between grid and list view in the library and the explore search results",
			"Sort and filter series the same way you sort books: by title, author, progress, or recent",
			"Explore now shows popular titles per provider when you haven't typed a search yet",
			"Download all pending chapters at once from the series detail page, with live progress and a cancel button",
			"Open the current chapter on the source website straight from the reader overflow menu",
		],
	},
	{
		date: "2026-04-28",
		title: "Glossary",
		tags: ["App"],
		changes: [
			"Keep track of names, places, and ideas with a per-book glossary",
			"Select a word in the reader and tap 'Add to glossary' to save an entry",
			"Each entry gets a colored avatar with initials so they're easy to scan",
			"Words that match an entry are subtly marked in the text. Tap one to open the entry",
			"Contents, Highlights and Glossary now live in one annotations sheet",
			"Toggle the glossary marks in the appearance popover if you'd rather not see them",
			"Choose whether an entry is just for one book or available everywhere",
			"Glossary entries sync across devices, same as highlights",
			"This dialog now shows what's new whenever you open the app after an update",
		],
	},
	{
		date: "2026-04-27",
		title: "Page Reader and a few rough edges",
		tags: ["App"],
		changes: [
			"You can now read in pages instead of one long scroll",
			"Switch between page and scroll right from the appearance popover",
			"New app font size setting if the UI feels too small or too big",
			"Importing books got smoother, with clearer toasts when something goes wrong",
			"Really long words no longer get cut off in RSVP mode",
			"Fixed onboarding being hard to scroll on smaller phones",
			"Fixed a case where deleting a book left things in a weird state",
			"Cleaned up how settings sync to the cloud",
		],
	},
	{
		date: "2026-04-23",
		title: "More Ways to Import: URLs, PDFs, Share Intent",
		tags: ["App"],
		changes: [
			"Paste any article URL to import it as a cleanly-extracted book",
			"Share any webpage or text to Lesefluss from the Android share sheet",
			"PDF import with metadata, cover from page 1, and chapters from bookmarks",
			"Import HTML files through the file picker",
			"Paste plain text from the clipboard as a new book",
			"Redesigned import picker with clearer source labels and descriptions",
		],
	},
	{
		date: "2026-04-22",
		title: "Reader Redesign & Onboarding",
		tags: ["App"],
		changes: [
			"Guided onboarding flow: welcome, speed, theme, reader mode, and sync steps",
			"Optional 'Start with a classic' onboarding step — tap public-domain classics to seed your library",
			"Toggle to hide the active-word underline in the scroll reader",
			"RSVP view re-centred so the focal letter sits in the middle again",
			"Rebuilt RSVP reader with cleaner controls and smoother transitions",
			"Live RSVP preview in the settings screen",
			"Refined sepia theme with better contrast across the app",
			"Fixed RSVP focal letter x-offset setting",
		],
	},
	{
		date: "2026-04-21",
		title: "Play Store Beta & Polish",
		tags: ["App", "Website"],
		changes: [
			"Google Play Store listing link on the download page",
			"Smoother closed-beta request flow",
			"Session handling fixes and formatting polish",
			"Privacy policy updates",
		],
	},
	{
		date: "2026-04-20",
		title: "OAuth, Mobile Login & APK Releases",
		tags: ["App", "Website"],
		changes: [
			"Google and Discord OAuth sign-in",
			"Email verification for new accounts",
			"Mobile login with deep-link callback back into the app",
			"BLE toggle in device settings to disable Bluetooth scanning",
			"Automated APK release pipeline with signed builds",
			"New download page and website login hint for web-app visitors",
		],
	},
	{
		date: "2026-04-19",
		title: "Explore Tab: Discover Public-Domain Books",
		tags: ["App", "Website"],
		changes: [
			"Browse thousands of free books from Project Gutenberg and Standard Ebooks",
			"Landing page with featured, classics, most-read, and random shelves",
			"Rotating featured hero with manual navigation",
			"Genre filtering across 8 curated categories",
			"Full-text search with typo tolerance and language filter",
			"Classic page-number pagination with auto scroll-to-top",
			"One-tap download to import a book into your library",
			"Polished book detail pages with source badge and descriptions",
			"Smooth cover loading with skeleton shimmer and async decoding",
		],
	},
	{
		date: "2026-04-18",
		title: "Profile, Admin & Analytics",
		tags: ["Website"],
		changes: [
			"Public profile page with reading stats, library, and highlights",
			"Account page for password management and danger zone",
			"Admin dashboard for user and book management",
			"Web app highlighting support",
			"Analytics integration and SEO hardening (CSP, security headers)",
			"App icon and OG image",
		],
	},
	{
		date: "2026-04-15",
		title: "Web App & Cloud Sync",
		tags: ["App", "Website"],
		changes: [
			"Web app live at lesefluss.app/app - full reader in the browser",
			"Cloud sync: books, settings, and highlights backed up automatically",
			"Desktop sidebar navigation for the web version",
			"Privacy policy, Terms of Service, and Imprint pages",
		],
	},
	{
		date: "2026-04-13",
		title: "In-App RSVP Reader, Highlights & Library",
		tags: ["App"],
		changes: [
			"Full RSVP reader in the mobile app (software parity with ESP32)",
			"Reading themes: dark, sepia, light",
			"Progress bar with tap and drag scrubbing",
			"Highlight and annotate text with color swatches",
			"Dictionary lookup via tap on any word",
			"Library sorting and filtering (title, author, progress, date)",
			"Reading time estimation",
		],
	},
	{
		date: "2026-04-08",
		title: "AMOLED Display & Device Polish",
		tags: ["ESP32", "App"],
		changes: [
			"AMOLED (RM67162) display support alongside ST7789",
			"Encoder scrubbing mode: rotate to step through words",
			"Keep display on during book transfer",
			"Fixed BLE window-size issue on AMOLED boards",
			"Transfer wake: display activates automatically during upload",
		],
	},
	{
		date: "2026-04-03",
		title: "ESP32 Deep Sleep & Brightness",
		tags: ["ESP32"],
		changes: [
			"Deep sleep with configurable idle timeout - weeks of battery life",
			"Brightness control (10–100 %) synced from the app",
			"Dark / inverse mode support on device",
			"ESP32 firmware simplified and restructured; WiFi removed",
			"Improved BLE connection stability",
		],
	},
	{
		date: "2026-03-26",
		title: "Initial Release",
		tags: ["App", "ESP32"],
		changes: [
			"Core RSVP reader on ESP32 with focal letter (ORP) positioning",
			"Companion mobile app: settings sync over BLE",
			"EPUB and TXT book import",
			"Chunked BLE book transfer to device",
			"Bidirectional position sync between device and app",
			"Library with metadata and cover extraction",
			"Auto-connect to last paired device",
		],
	},
];
