/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabsSocialIndexRouteImport } from './routes/tabs/social/index'
import { Route as TabsSettingsIndexRouteImport } from './routes/tabs/settings/index'
import { Route as TabsLibraryIndexRouteImport } from './routes/tabs/library/index'
import { Route as TabsExploreIndexRouteImport } from './routes/tabs/explore/index'
import { Route as TabsSocialInviteLinkRouteImport } from './routes/tabs/social/invite-link'
import { Route as TabsSocialInboxRouteImport } from './routes/tabs/social/inbox'
import { Route as TabsSocialBuddyReadsRouteImport } from './routes/tabs/social/buddy-reads'
import { Route as TabsSocialBlockedRouteImport } from './routes/tabs/social/blocked'
import { Route as TabsSettingsSyncRouteImport } from './routes/tabs/settings/sync'
import { Route as TabsSettingsSocialRouteImport } from './routes/tabs/settings/social'
import { Route as TabsSettingsRsvpRouteImport } from './routes/tabs/settings/rsvp'
import { Route as TabsSettingsReaderRouteImport } from './routes/tabs/settings/reader'
import { Route as TabsSettingsNotificationsRouteImport } from './routes/tabs/settings/notifications'
import { Route as TabsSettingsGeneralRouteImport } from './routes/tabs/settings/general'
import { Route as TabsSettingsExportRouteImport } from './routes/tabs/settings/export'
import { Route as TabsSettingsDeviceRouteImport } from './routes/tabs/settings/device'
import { Route as TabsReaderIdRouteImport } from './routes/tabs/reader.$id'
import { Route as TabsLibraryStatsRouteImport } from './routes/tabs/library/stats'
import { Route as TabsExploreWebNovelsRouteImport } from './routes/tabs/explore/web-novels'
import { Route as TabsExploreWebNovelPreviewRouteImport } from './routes/tabs/explore/web-novel-preview'
import { Route as TabsExploreTagsRouteImport } from './routes/tabs/explore/tags'
import { Route as TabsSocialProfileUserIdRouteImport } from './routes/tabs/social/profile.$userId'
import { Route as TabsSocialInviteTokenRouteImport } from './routes/tabs/social/invite.$token'
import { Route as TabsSocialBuddyReadIdRouteImport } from './routes/tabs/social/buddy-read.$id'
import { Route as TabsSocialBuddyReadDiscussionIdRouteImport } from './routes/tabs/social/buddy-read-discussion.$id'
import { Route as TabsLibrarySeriesIdRouteImport } from './routes/tabs/library/series.$id'
import { Route as TabsLibraryBookIdRouteImport } from './routes/tabs/library/book.$id'
import { Route as TabsExploreBookCatalogIdRouteImport } from './routes/tabs/explore/book.$catalogId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSocialIndexRoute = TabsSocialIndexRouteImport.update({
  id: '/tabs/social/',
  path: '/tabs/social/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSettingsIndexRoute = TabsSettingsIndexRouteImport.update({
  id: '/tabs/settings/',
  path: '/tabs/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsLibraryIndexRoute = TabsLibraryIndexRouteImport.update({
  id: '/tabs/library/',
  path: '/tabs/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsExploreIndexRoute = TabsExploreIndexRouteImport.update({
  id: '/tabs/explore/',
  path: '/tabs/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSocialInviteLinkRoute = TabsSocialInviteLinkRouteImport.update({
  id: '/tabs/social/invite-link',
  path: '/tabs/social/invite-link',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSocialInboxRoute = TabsSocialInboxRouteImport.update({
  id: '/tabs/social/inbox',
  path: '/tabs/social/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSocialBuddyReadsRoute = TabsSocialBuddyReadsRouteImport.update({
  id: '/tabs/social/buddy-reads',
  path: '/tabs/social/buddy-reads',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSocialBlockedRoute = TabsSocialBlockedRouteImport.update({
  id: '/tabs/social/blocked',
  path: '/tabs/social/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSettingsSyncRoute = TabsSettingsSyncRouteImport.update({
  id: '/tabs/settings/sync',
  path: '/tabs/settings/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSettingsSocialRoute = TabsSettingsSocialRouteImport.update({
  id: '/tabs/settings/social',
  path: '/tabs/settings/social',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSettingsRsvpRoute = TabsSettingsRsvpRouteImport.update({
  id: '/tabs/settings/rsvp',
  path: '/tabs/settings/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSettingsReaderRoute = TabsSettingsReaderRouteImport.update({
  id: '/tabs/settings/reader',
  path: '/tabs/settings/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSettingsNotificationsRoute =
  TabsSettingsNotificationsRouteImport.update({
    id: '/tabs/settings/notifications',
    path: '/tabs/settings/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const TabsSettingsGeneralRoute = TabsSettingsGeneralRouteImport.update({
  id: '/tabs/settings/general',
  path: '/tabs/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSettingsExportRoute = TabsSettingsExportRouteImport.update({
  id: '/tabs/settings/export',
  path: '/tabs/settings/export',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSettingsDeviceRoute = TabsSettingsDeviceRouteImport.update({
  id: '/tabs/settings/device',
  path: '/tabs/settings/device',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsReaderIdRoute = TabsReaderIdRouteImport.update({
  id: '/tabs/reader/$id',
  path: '/tabs/reader/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsLibraryStatsRoute = TabsLibraryStatsRouteImport.update({
  id: '/tabs/library/stats',
  path: '/tabs/library/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsExploreWebNovelsRoute = TabsExploreWebNovelsRouteImport.update({
  id: '/tabs/explore/web-novels',
  path: '/tabs/explore/web-novels',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsExploreWebNovelPreviewRoute =
  TabsExploreWebNovelPreviewRouteImport.update({
    id: '/tabs/explore/web-novel-preview',
    path: '/tabs/explore/web-novel-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const TabsExploreTagsRoute = TabsExploreTagsRouteImport.update({
  id: '/tabs/explore/tags',
  path: '/tabs/explore/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSocialProfileUserIdRoute = TabsSocialProfileUserIdRouteImport.update({
  id: '/tabs/social/profile/$userId',
  path: '/tabs/social/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSocialInviteTokenRoute = TabsSocialInviteTokenRouteImport.update({
  id: '/tabs/social/invite/$token',
  path: '/tabs/social/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSocialBuddyReadIdRoute = TabsSocialBuddyReadIdRouteImport.update({
  id: '/tabs/social/buddy-read/$id',
  path: '/tabs/social/buddy-read/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSocialBuddyReadDiscussionIdRoute =
  TabsSocialBuddyReadDiscussionIdRouteImport.update({
    id: '/tabs/social/buddy-read-discussion/$id',
    path: '/tabs/social/buddy-read-discussion/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const TabsLibrarySeriesIdRoute = TabsLibrarySeriesIdRouteImport.update({
  id: '/tabs/library/series/$id',
  path: '/tabs/library/series/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsLibraryBookIdRoute = TabsLibraryBookIdRouteImport.update({
  id: '/tabs/library/book/$id',
  path: '/tabs/library/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsExploreBookCatalogIdRoute =
  TabsExploreBookCatalogIdRouteImport.update({
    id: '/tabs/explore/book/$catalogId',
    path: '/tabs/explore/book/$catalogId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/tabs/explore/tags': typeof TabsExploreTagsRoute
  '/tabs/explore/web-novel-preview': typeof TabsExploreWebNovelPreviewRoute
  '/tabs/explore/web-novels': typeof TabsExploreWebNovelsRoute
  '/tabs/library/stats': typeof TabsLibraryStatsRoute
  '/tabs/reader/$id': typeof TabsReaderIdRoute
  '/tabs/settings/device': typeof TabsSettingsDeviceRoute
  '/tabs/settings/export': typeof TabsSettingsExportRoute
  '/tabs/settings/general': typeof TabsSettingsGeneralRoute
  '/tabs/settings/notifications': typeof TabsSettingsNotificationsRoute
  '/tabs/settings/reader': typeof TabsSettingsReaderRoute
  '/tabs/settings/rsvp': typeof TabsSettingsRsvpRoute
  '/tabs/settings/social': typeof TabsSettingsSocialRoute
  '/tabs/settings/sync': typeof TabsSettingsSyncRoute
  '/tabs/social/blocked': typeof TabsSocialBlockedRoute
  '/tabs/social/buddy-reads': typeof TabsSocialBuddyReadsRoute
  '/tabs/social/inbox': typeof TabsSocialInboxRoute
  '/tabs/social/invite-link': typeof TabsSocialInviteLinkRoute
  '/tabs/explore/': typeof TabsExploreIndexRoute
  '/tabs/library/': typeof TabsLibraryIndexRoute
  '/tabs/settings/': typeof TabsSettingsIndexRoute
  '/tabs/social/': typeof TabsSocialIndexRoute
  '/tabs/explore/book/$catalogId': typeof TabsExploreBookCatalogIdRoute
  '/tabs/library/book/$id': typeof TabsLibraryBookIdRoute
  '/tabs/library/series/$id': typeof TabsLibrarySeriesIdRoute
  '/tabs/social/buddy-read-discussion/$id': typeof TabsSocialBuddyReadDiscussionIdRoute
  '/tabs/social/buddy-read/$id': typeof TabsSocialBuddyReadIdRoute
  '/tabs/social/invite/$token': typeof TabsSocialInviteTokenRoute
  '/tabs/social/profile/$userId': typeof TabsSocialProfileUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/tabs/explore/tags': typeof TabsExploreTagsRoute
  '/tabs/explore/web-novel-preview': typeof TabsExploreWebNovelPreviewRoute
  '/tabs/explore/web-novels': typeof TabsExploreWebNovelsRoute
  '/tabs/library/stats': typeof TabsLibraryStatsRoute
  '/tabs/reader/$id': typeof TabsReaderIdRoute
  '/tabs/settings/device': typeof TabsSettingsDeviceRoute
  '/tabs/settings/export': typeof TabsSettingsExportRoute
  '/tabs/settings/general': typeof TabsSettingsGeneralRoute
  '/tabs/settings/notifications': typeof TabsSettingsNotificationsRoute
  '/tabs/settings/reader': typeof TabsSettingsReaderRoute
  '/tabs/settings/rsvp': typeof TabsSettingsRsvpRoute
  '/tabs/settings/social': typeof TabsSettingsSocialRoute
  '/tabs/settings/sync': typeof TabsSettingsSyncRoute
  '/tabs/social/blocked': typeof TabsSocialBlockedRoute
  '/tabs/social/buddy-reads': typeof TabsSocialBuddyReadsRoute
  '/tabs/social/inbox': typeof TabsSocialInboxRoute
  '/tabs/social/invite-link': typeof TabsSocialInviteLinkRoute
  '/tabs/explore': typeof TabsExploreIndexRoute
  '/tabs/library': typeof TabsLibraryIndexRoute
  '/tabs/settings': typeof TabsSettingsIndexRoute
  '/tabs/social': typeof TabsSocialIndexRoute
  '/tabs/explore/book/$catalogId': typeof TabsExploreBookCatalogIdRoute
  '/tabs/library/book/$id': typeof TabsLibraryBookIdRoute
  '/tabs/library/series/$id': typeof TabsLibrarySeriesIdRoute
  '/tabs/social/buddy-read-discussion/$id': typeof TabsSocialBuddyReadDiscussionIdRoute
  '/tabs/social/buddy-read/$id': typeof TabsSocialBuddyReadIdRoute
  '/tabs/social/invite/$token': typeof TabsSocialInviteTokenRoute
  '/tabs/social/profile/$userId': typeof TabsSocialProfileUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/tabs/explore/tags': typeof TabsExploreTagsRoute
  '/tabs/explore/web-novel-preview': typeof TabsExploreWebNovelPreviewRoute
  '/tabs/explore/web-novels': typeof TabsExploreWebNovelsRoute
  '/tabs/library/stats': typeof TabsLibraryStatsRoute
  '/tabs/reader/$id': typeof TabsReaderIdRoute
  '/tabs/settings/device': typeof TabsSettingsDeviceRoute
  '/tabs/settings/export': typeof TabsSettingsExportRoute
  '/tabs/settings/general': typeof TabsSettingsGeneralRoute
  '/tabs/settings/notifications': typeof TabsSettingsNotificationsRoute
  '/tabs/settings/reader': typeof TabsSettingsReaderRoute
  '/tabs/settings/rsvp': typeof TabsSettingsRsvpRoute
  '/tabs/settings/social': typeof TabsSettingsSocialRoute
  '/tabs/settings/sync': typeof TabsSettingsSyncRoute
  '/tabs/social/blocked': typeof TabsSocialBlockedRoute
  '/tabs/social/buddy-reads': typeof TabsSocialBuddyReadsRoute
  '/tabs/social/inbox': typeof TabsSocialInboxRoute
  '/tabs/social/invite-link': typeof TabsSocialInviteLinkRoute
  '/tabs/explore/': typeof TabsExploreIndexRoute
  '/tabs/library/': typeof TabsLibraryIndexRoute
  '/tabs/settings/': typeof TabsSettingsIndexRoute
  '/tabs/social/': typeof TabsSocialIndexRoute
  '/tabs/explore/book/$catalogId': typeof TabsExploreBookCatalogIdRoute
  '/tabs/library/book/$id': typeof TabsLibraryBookIdRoute
  '/tabs/library/series/$id': typeof TabsLibrarySeriesIdRoute
  '/tabs/social/buddy-read-discussion/$id': typeof TabsSocialBuddyReadDiscussionIdRoute
  '/tabs/social/buddy-read/$id': typeof TabsSocialBuddyReadIdRoute
  '/tabs/social/invite/$token': typeof TabsSocialInviteTokenRoute
  '/tabs/social/profile/$userId': typeof TabsSocialProfileUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/tabs/explore/tags'
    | '/tabs/explore/web-novel-preview'
    | '/tabs/explore/web-novels'
    | '/tabs/library/stats'
    | '/tabs/reader/$id'
    | '/tabs/settings/device'
    | '/tabs/settings/export'
    | '/tabs/settings/general'
    | '/tabs/settings/notifications'
    | '/tabs/settings/reader'
    | '/tabs/settings/rsvp'
    | '/tabs/settings/social'
    | '/tabs/settings/sync'
    | '/tabs/social/blocked'
    | '/tabs/social/buddy-reads'
    | '/tabs/social/inbox'
    | '/tabs/social/invite-link'
    | '/tabs/explore/'
    | '/tabs/library/'
    | '/tabs/settings/'
    | '/tabs/social/'
    | '/tabs/explore/book/$catalogId'
    | '/tabs/library/book/$id'
    | '/tabs/library/series/$id'
    | '/tabs/social/buddy-read-discussion/$id'
    | '/tabs/social/buddy-read/$id'
    | '/tabs/social/invite/$token'
    | '/tabs/social/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/tabs/explore/tags'
    | '/tabs/explore/web-novel-preview'
    | '/tabs/explore/web-novels'
    | '/tabs/library/stats'
    | '/tabs/reader/$id'
    | '/tabs/settings/device'
    | '/tabs/settings/export'
    | '/tabs/settings/general'
    | '/tabs/settings/notifications'
    | '/tabs/settings/reader'
    | '/tabs/settings/rsvp'
    | '/tabs/settings/social'
    | '/tabs/settings/sync'
    | '/tabs/social/blocked'
    | '/tabs/social/buddy-reads'
    | '/tabs/social/inbox'
    | '/tabs/social/invite-link'
    | '/tabs/explore'
    | '/tabs/library'
    | '/tabs/settings'
    | '/tabs/social'
    | '/tabs/explore/book/$catalogId'
    | '/tabs/library/book/$id'
    | '/tabs/library/series/$id'
    | '/tabs/social/buddy-read-discussion/$id'
    | '/tabs/social/buddy-read/$id'
    | '/tabs/social/invite/$token'
    | '/tabs/social/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/tabs/explore/tags'
    | '/tabs/explore/web-novel-preview'
    | '/tabs/explore/web-novels'
    | '/tabs/library/stats'
    | '/tabs/reader/$id'
    | '/tabs/settings/device'
    | '/tabs/settings/export'
    | '/tabs/settings/general'
    | '/tabs/settings/notifications'
    | '/tabs/settings/reader'
    | '/tabs/settings/rsvp'
    | '/tabs/settings/social'
    | '/tabs/settings/sync'
    | '/tabs/social/blocked'
    | '/tabs/social/buddy-reads'
    | '/tabs/social/inbox'
    | '/tabs/social/invite-link'
    | '/tabs/explore/'
    | '/tabs/library/'
    | '/tabs/settings/'
    | '/tabs/social/'
    | '/tabs/explore/book/$catalogId'
    | '/tabs/library/book/$id'
    | '/tabs/library/series/$id'
    | '/tabs/social/buddy-read-discussion/$id'
    | '/tabs/social/buddy-read/$id'
    | '/tabs/social/invite/$token'
    | '/tabs/social/profile/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  TabsExploreTagsRoute: typeof TabsExploreTagsRoute
  TabsExploreWebNovelPreviewRoute: typeof TabsExploreWebNovelPreviewRoute
  TabsExploreWebNovelsRoute: typeof TabsExploreWebNovelsRoute
  TabsLibraryStatsRoute: typeof TabsLibraryStatsRoute
  TabsReaderIdRoute: typeof TabsReaderIdRoute
  TabsSettingsDeviceRoute: typeof TabsSettingsDeviceRoute
  TabsSettingsExportRoute: typeof TabsSettingsExportRoute
  TabsSettingsGeneralRoute: typeof TabsSettingsGeneralRoute
  TabsSettingsNotificationsRoute: typeof TabsSettingsNotificationsRoute
  TabsSettingsReaderRoute: typeof TabsSettingsReaderRoute
  TabsSettingsRsvpRoute: typeof TabsSettingsRsvpRoute
  TabsSettingsSocialRoute: typeof TabsSettingsSocialRoute
  TabsSettingsSyncRoute: typeof TabsSettingsSyncRoute
  TabsSocialBlockedRoute: typeof TabsSocialBlockedRoute
  TabsSocialBuddyReadsRoute: typeof TabsSocialBuddyReadsRoute
  TabsSocialInboxRoute: typeof TabsSocialInboxRoute
  TabsSocialInviteLinkRoute: typeof TabsSocialInviteLinkRoute
  TabsExploreIndexRoute: typeof TabsExploreIndexRoute
  TabsLibraryIndexRoute: typeof TabsLibraryIndexRoute
  TabsSettingsIndexRoute: typeof TabsSettingsIndexRoute
  TabsSocialIndexRoute: typeof TabsSocialIndexRoute
  TabsExploreBookCatalogIdRoute: typeof TabsExploreBookCatalogIdRoute
  TabsLibraryBookIdRoute: typeof TabsLibraryBookIdRoute
  TabsLibrarySeriesIdRoute: typeof TabsLibrarySeriesIdRoute
  TabsSocialBuddyReadDiscussionIdRoute: typeof TabsSocialBuddyReadDiscussionIdRoute
  TabsSocialBuddyReadIdRoute: typeof TabsSocialBuddyReadIdRoute
  TabsSocialInviteTokenRoute: typeof TabsSocialInviteTokenRoute
  TabsSocialProfileUserIdRoute: typeof TabsSocialProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/social/': {
      id: '/tabs/social/'
      path: '/tabs/social'
      fullPath: '/tabs/social/'
      preLoaderRoute: typeof TabsSocialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/settings/': {
      id: '/tabs/settings/'
      path: '/tabs/settings'
      fullPath: '/tabs/settings/'
      preLoaderRoute: typeof TabsSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/library/': {
      id: '/tabs/library/'
      path: '/tabs/library'
      fullPath: '/tabs/library/'
      preLoaderRoute: typeof TabsLibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/explore/': {
      id: '/tabs/explore/'
      path: '/tabs/explore'
      fullPath: '/tabs/explore/'
      preLoaderRoute: typeof TabsExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/social/invite-link': {
      id: '/tabs/social/invite-link'
      path: '/tabs/social/invite-link'
      fullPath: '/tabs/social/invite-link'
      preLoaderRoute: typeof TabsSocialInviteLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/social/inbox': {
      id: '/tabs/social/inbox'
      path: '/tabs/social/inbox'
      fullPath: '/tabs/social/inbox'
      preLoaderRoute: typeof TabsSocialInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/social/buddy-reads': {
      id: '/tabs/social/buddy-reads'
      path: '/tabs/social/buddy-reads'
      fullPath: '/tabs/social/buddy-reads'
      preLoaderRoute: typeof TabsSocialBuddyReadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/social/blocked': {
      id: '/tabs/social/blocked'
      path: '/tabs/social/blocked'
      fullPath: '/tabs/social/blocked'
      preLoaderRoute: typeof TabsSocialBlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/settings/sync': {
      id: '/tabs/settings/sync'
      path: '/tabs/settings/sync'
      fullPath: '/tabs/settings/sync'
      preLoaderRoute: typeof TabsSettingsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/settings/social': {
      id: '/tabs/settings/social'
      path: '/tabs/settings/social'
      fullPath: '/tabs/settings/social'
      preLoaderRoute: typeof TabsSettingsSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/settings/rsvp': {
      id: '/tabs/settings/rsvp'
      path: '/tabs/settings/rsvp'
      fullPath: '/tabs/settings/rsvp'
      preLoaderRoute: typeof TabsSettingsRsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/settings/reader': {
      id: '/tabs/settings/reader'
      path: '/tabs/settings/reader'
      fullPath: '/tabs/settings/reader'
      preLoaderRoute: typeof TabsSettingsReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/settings/notifications': {
      id: '/tabs/settings/notifications'
      path: '/tabs/settings/notifications'
      fullPath: '/tabs/settings/notifications'
      preLoaderRoute: typeof TabsSettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/settings/general': {
      id: '/tabs/settings/general'
      path: '/tabs/settings/general'
      fullPath: '/tabs/settings/general'
      preLoaderRoute: typeof TabsSettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/settings/export': {
      id: '/tabs/settings/export'
      path: '/tabs/settings/export'
      fullPath: '/tabs/settings/export'
      preLoaderRoute: typeof TabsSettingsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/settings/device': {
      id: '/tabs/settings/device'
      path: '/tabs/settings/device'
      fullPath: '/tabs/settings/device'
      preLoaderRoute: typeof TabsSettingsDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/reader/$id': {
      id: '/tabs/reader/$id'
      path: '/tabs/reader/$id'
      fullPath: '/tabs/reader/$id'
      preLoaderRoute: typeof TabsReaderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/library/stats': {
      id: '/tabs/library/stats'
      path: '/tabs/library/stats'
      fullPath: '/tabs/library/stats'
      preLoaderRoute: typeof TabsLibraryStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/explore/web-novels': {
      id: '/tabs/explore/web-novels'
      path: '/tabs/explore/web-novels'
      fullPath: '/tabs/explore/web-novels'
      preLoaderRoute: typeof TabsExploreWebNovelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/explore/web-novel-preview': {
      id: '/tabs/explore/web-novel-preview'
      path: '/tabs/explore/web-novel-preview'
      fullPath: '/tabs/explore/web-novel-preview'
      preLoaderRoute: typeof TabsExploreWebNovelPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/explore/tags': {
      id: '/tabs/explore/tags'
      path: '/tabs/explore/tags'
      fullPath: '/tabs/explore/tags'
      preLoaderRoute: typeof TabsExploreTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/social/profile/$userId': {
      id: '/tabs/social/profile/$userId'
      path: '/tabs/social/profile/$userId'
      fullPath: '/tabs/social/profile/$userId'
      preLoaderRoute: typeof TabsSocialProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/social/invite/$token': {
      id: '/tabs/social/invite/$token'
      path: '/tabs/social/invite/$token'
      fullPath: '/tabs/social/invite/$token'
      preLoaderRoute: typeof TabsSocialInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/social/buddy-read/$id': {
      id: '/tabs/social/buddy-read/$id'
      path: '/tabs/social/buddy-read/$id'
      fullPath: '/tabs/social/buddy-read/$id'
      preLoaderRoute: typeof TabsSocialBuddyReadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/social/buddy-read-discussion/$id': {
      id: '/tabs/social/buddy-read-discussion/$id'
      path: '/tabs/social/buddy-read-discussion/$id'
      fullPath: '/tabs/social/buddy-read-discussion/$id'
      preLoaderRoute: typeof TabsSocialBuddyReadDiscussionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/library/series/$id': {
      id: '/tabs/library/series/$id'
      path: '/tabs/library/series/$id'
      fullPath: '/tabs/library/series/$id'
      preLoaderRoute: typeof TabsLibrarySeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/library/book/$id': {
      id: '/tabs/library/book/$id'
      path: '/tabs/library/book/$id'
      fullPath: '/tabs/library/book/$id'
      preLoaderRoute: typeof TabsLibraryBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/explore/book/$catalogId': {
      id: '/tabs/explore/book/$catalogId'
      path: '/tabs/explore/book/$catalogId'
      fullPath: '/tabs/explore/book/$catalogId'
      preLoaderRoute: typeof TabsExploreBookCatalogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  TabsExploreTagsRoute: TabsExploreTagsRoute,
  TabsExploreWebNovelPreviewRoute: TabsExploreWebNovelPreviewRoute,
  TabsExploreWebNovelsRoute: TabsExploreWebNovelsRoute,
  TabsLibraryStatsRoute: TabsLibraryStatsRoute,
  TabsReaderIdRoute: TabsReaderIdRoute,
  TabsSettingsDeviceRoute: TabsSettingsDeviceRoute,
  TabsSettingsExportRoute: TabsSettingsExportRoute,
  TabsSettingsGeneralRoute: TabsSettingsGeneralRoute,
  TabsSettingsNotificationsRoute: TabsSettingsNotificationsRoute,
  TabsSettingsReaderRoute: TabsSettingsReaderRoute,
  TabsSettingsRsvpRoute: TabsSettingsRsvpRoute,
  TabsSettingsSocialRoute: TabsSettingsSocialRoute,
  TabsSettingsSyncRoute: TabsSettingsSyncRoute,
  TabsSocialBlockedRoute: TabsSocialBlockedRoute,
  TabsSocialBuddyReadsRoute: TabsSocialBuddyReadsRoute,
  TabsSocialInboxRoute: TabsSocialInboxRoute,
  TabsSocialInviteLinkRoute: TabsSocialInviteLinkRoute,
  TabsExploreIndexRoute: TabsExploreIndexRoute,
  TabsLibraryIndexRoute: TabsLibraryIndexRoute,
  TabsSettingsIndexRoute: TabsSettingsIndexRoute,
  TabsSocialIndexRoute: TabsSocialIndexRoute,
  TabsExploreBookCatalogIdRoute: TabsExploreBookCatalogIdRoute,
  TabsLibraryBookIdRoute: TabsLibraryBookIdRoute,
  TabsLibrarySeriesIdRoute: TabsLibrarySeriesIdRoute,
  TabsSocialBuddyReadDiscussionIdRoute: TabsSocialBuddyReadDiscussionIdRoute,
  TabsSocialBuddyReadIdRoute: TabsSocialBuddyReadIdRoute,
  TabsSocialInviteTokenRoute: TabsSocialInviteTokenRoute,
  TabsSocialProfileUserIdRoute: TabsSocialProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
