/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabsSettingsIndexRouteImport } from './routes/tabs/settings/index'
import { Route as TabsLibraryIndexRouteImport } from './routes/tabs/library/index'
import { Route as TabsExploreIndexRouteImport } from './routes/tabs/explore/index'
import { Route as TabsSettingsSyncRouteImport } from './routes/tabs/settings/sync'
import { Route as TabsSettingsRsvpRouteImport } from './routes/tabs/settings/rsvp'
import { Route as TabsSettingsExportRouteImport } from './routes/tabs/settings/export'
import { Route as TabsSettingsDeviceRouteImport } from './routes/tabs/settings/device'
import { Route as TabsSettingsAppearanceRouteImport } from './routes/tabs/settings/appearance'
import { Route as TabsReaderIdRouteImport } from './routes/tabs/reader.$id'
import { Route as TabsLibraryStatsRouteImport } from './routes/tabs/library/stats'
import { Route as TabsExploreWebNovelsRouteImport } from './routes/tabs/explore/web-novels'
import { Route as TabsExploreWebNovelPreviewRouteImport } from './routes/tabs/explore/web-novel-preview'
import { Route as TabsLibrarySeriesIdRouteImport } from './routes/tabs/library/series.$id'
import { Route as TabsLibraryBookIdRouteImport } from './routes/tabs/library/book.$id'
import { Route as TabsExploreBookCatalogIdRouteImport } from './routes/tabs/explore/book.$catalogId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSettingsIndexRoute = TabsSettingsIndexRouteImport.update({
  id: '/tabs/settings/',
  path: '/tabs/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsLibraryIndexRoute = TabsLibraryIndexRouteImport.update({
  id: '/tabs/library/',
  path: '/tabs/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsExploreIndexRoute = TabsExploreIndexRouteImport.update({
  id: '/tabs/explore/',
  path: '/tabs/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSettingsSyncRoute = TabsSettingsSyncRouteImport.update({
  id: '/tabs/settings/sync',
  path: '/tabs/settings/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSettingsRsvpRoute = TabsSettingsRsvpRouteImport.update({
  id: '/tabs/settings/rsvp',
  path: '/tabs/settings/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSettingsExportRoute = TabsSettingsExportRouteImport.update({
  id: '/tabs/settings/export',
  path: '/tabs/settings/export',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSettingsDeviceRoute = TabsSettingsDeviceRouteImport.update({
  id: '/tabs/settings/device',
  path: '/tabs/settings/device',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSettingsAppearanceRoute = TabsSettingsAppearanceRouteImport.update({
  id: '/tabs/settings/appearance',
  path: '/tabs/settings/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsReaderIdRoute = TabsReaderIdRouteImport.update({
  id: '/tabs/reader/$id',
  path: '/tabs/reader/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsLibraryStatsRoute = TabsLibraryStatsRouteImport.update({
  id: '/tabs/library/stats',
  path: '/tabs/library/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsExploreWebNovelsRoute = TabsExploreWebNovelsRouteImport.update({
  id: '/tabs/explore/web-novels',
  path: '/tabs/explore/web-novels',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsExploreWebNovelPreviewRoute =
  TabsExploreWebNovelPreviewRouteImport.update({
    id: '/tabs/explore/web-novel-preview',
    path: '/tabs/explore/web-novel-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const TabsLibrarySeriesIdRoute = TabsLibrarySeriesIdRouteImport.update({
  id: '/tabs/library/series/$id',
  path: '/tabs/library/series/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsLibraryBookIdRoute = TabsLibraryBookIdRouteImport.update({
  id: '/tabs/library/book/$id',
  path: '/tabs/library/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsExploreBookCatalogIdRoute =
  TabsExploreBookCatalogIdRouteImport.update({
    id: '/tabs/explore/book/$catalogId',
    path: '/tabs/explore/book/$catalogId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/tabs/explore/web-novel-preview': typeof TabsExploreWebNovelPreviewRoute
  '/tabs/explore/web-novels': typeof TabsExploreWebNovelsRoute
  '/tabs/library/stats': typeof TabsLibraryStatsRoute
  '/tabs/reader/$id': typeof TabsReaderIdRoute
  '/tabs/settings/appearance': typeof TabsSettingsAppearanceRoute
  '/tabs/settings/device': typeof TabsSettingsDeviceRoute
  '/tabs/settings/export': typeof TabsSettingsExportRoute
  '/tabs/settings/rsvp': typeof TabsSettingsRsvpRoute
  '/tabs/settings/sync': typeof TabsSettingsSyncRoute
  '/tabs/explore/': typeof TabsExploreIndexRoute
  '/tabs/library/': typeof TabsLibraryIndexRoute
  '/tabs/settings/': typeof TabsSettingsIndexRoute
  '/tabs/explore/book/$catalogId': typeof TabsExploreBookCatalogIdRoute
  '/tabs/library/book/$id': typeof TabsLibraryBookIdRoute
  '/tabs/library/series/$id': typeof TabsLibrarySeriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/tabs/explore/web-novel-preview': typeof TabsExploreWebNovelPreviewRoute
  '/tabs/explore/web-novels': typeof TabsExploreWebNovelsRoute
  '/tabs/library/stats': typeof TabsLibraryStatsRoute
  '/tabs/reader/$id': typeof TabsReaderIdRoute
  '/tabs/settings/appearance': typeof TabsSettingsAppearanceRoute
  '/tabs/settings/device': typeof TabsSettingsDeviceRoute
  '/tabs/settings/export': typeof TabsSettingsExportRoute
  '/tabs/settings/rsvp': typeof TabsSettingsRsvpRoute
  '/tabs/settings/sync': typeof TabsSettingsSyncRoute
  '/tabs/explore': typeof TabsExploreIndexRoute
  '/tabs/library': typeof TabsLibraryIndexRoute
  '/tabs/settings': typeof TabsSettingsIndexRoute
  '/tabs/explore/book/$catalogId': typeof TabsExploreBookCatalogIdRoute
  '/tabs/library/book/$id': typeof TabsLibraryBookIdRoute
  '/tabs/library/series/$id': typeof TabsLibrarySeriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/tabs/explore/web-novel-preview': typeof TabsExploreWebNovelPreviewRoute
  '/tabs/explore/web-novels': typeof TabsExploreWebNovelsRoute
  '/tabs/library/stats': typeof TabsLibraryStatsRoute
  '/tabs/reader/$id': typeof TabsReaderIdRoute
  '/tabs/settings/appearance': typeof TabsSettingsAppearanceRoute
  '/tabs/settings/device': typeof TabsSettingsDeviceRoute
  '/tabs/settings/export': typeof TabsSettingsExportRoute
  '/tabs/settings/rsvp': typeof TabsSettingsRsvpRoute
  '/tabs/settings/sync': typeof TabsSettingsSyncRoute
  '/tabs/explore/': typeof TabsExploreIndexRoute
  '/tabs/library/': typeof TabsLibraryIndexRoute
  '/tabs/settings/': typeof TabsSettingsIndexRoute
  '/tabs/explore/book/$catalogId': typeof TabsExploreBookCatalogIdRoute
  '/tabs/library/book/$id': typeof TabsLibraryBookIdRoute
  '/tabs/library/series/$id': typeof TabsLibrarySeriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/tabs/explore/web-novel-preview'
    | '/tabs/explore/web-novels'
    | '/tabs/library/stats'
    | '/tabs/reader/$id'
    | '/tabs/settings/appearance'
    | '/tabs/settings/device'
    | '/tabs/settings/export'
    | '/tabs/settings/rsvp'
    | '/tabs/settings/sync'
    | '/tabs/explore/'
    | '/tabs/library/'
    | '/tabs/settings/'
    | '/tabs/explore/book/$catalogId'
    | '/tabs/library/book/$id'
    | '/tabs/library/series/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/tabs/explore/web-novel-preview'
    | '/tabs/explore/web-novels'
    | '/tabs/library/stats'
    | '/tabs/reader/$id'
    | '/tabs/settings/appearance'
    | '/tabs/settings/device'
    | '/tabs/settings/export'
    | '/tabs/settings/rsvp'
    | '/tabs/settings/sync'
    | '/tabs/explore'
    | '/tabs/library'
    | '/tabs/settings'
    | '/tabs/explore/book/$catalogId'
    | '/tabs/library/book/$id'
    | '/tabs/library/series/$id'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/tabs/explore/web-novel-preview'
    | '/tabs/explore/web-novels'
    | '/tabs/library/stats'
    | '/tabs/reader/$id'
    | '/tabs/settings/appearance'
    | '/tabs/settings/device'
    | '/tabs/settings/export'
    | '/tabs/settings/rsvp'
    | '/tabs/settings/sync'
    | '/tabs/explore/'
    | '/tabs/library/'
    | '/tabs/settings/'
    | '/tabs/explore/book/$catalogId'
    | '/tabs/library/book/$id'
    | '/tabs/library/series/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  TabsExploreWebNovelPreviewRoute: typeof TabsExploreWebNovelPreviewRoute
  TabsExploreWebNovelsRoute: typeof TabsExploreWebNovelsRoute
  TabsLibraryStatsRoute: typeof TabsLibraryStatsRoute
  TabsReaderIdRoute: typeof TabsReaderIdRoute
  TabsSettingsAppearanceRoute: typeof TabsSettingsAppearanceRoute
  TabsSettingsDeviceRoute: typeof TabsSettingsDeviceRoute
  TabsSettingsExportRoute: typeof TabsSettingsExportRoute
  TabsSettingsRsvpRoute: typeof TabsSettingsRsvpRoute
  TabsSettingsSyncRoute: typeof TabsSettingsSyncRoute
  TabsExploreIndexRoute: typeof TabsExploreIndexRoute
  TabsLibraryIndexRoute: typeof TabsLibraryIndexRoute
  TabsSettingsIndexRoute: typeof TabsSettingsIndexRoute
  TabsExploreBookCatalogIdRoute: typeof TabsExploreBookCatalogIdRoute
  TabsLibraryBookIdRoute: typeof TabsLibraryBookIdRoute
  TabsLibrarySeriesIdRoute: typeof TabsLibrarySeriesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/settings/': {
      id: '/tabs/settings/'
      path: '/tabs/settings'
      fullPath: '/tabs/settings/'
      preLoaderRoute: typeof TabsSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/library/': {
      id: '/tabs/library/'
      path: '/tabs/library'
      fullPath: '/tabs/library/'
      preLoaderRoute: typeof TabsLibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/explore/': {
      id: '/tabs/explore/'
      path: '/tabs/explore'
      fullPath: '/tabs/explore/'
      preLoaderRoute: typeof TabsExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/settings/sync': {
      id: '/tabs/settings/sync'
      path: '/tabs/settings/sync'
      fullPath: '/tabs/settings/sync'
      preLoaderRoute: typeof TabsSettingsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/settings/rsvp': {
      id: '/tabs/settings/rsvp'
      path: '/tabs/settings/rsvp'
      fullPath: '/tabs/settings/rsvp'
      preLoaderRoute: typeof TabsSettingsRsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/settings/export': {
      id: '/tabs/settings/export'
      path: '/tabs/settings/export'
      fullPath: '/tabs/settings/export'
      preLoaderRoute: typeof TabsSettingsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/settings/device': {
      id: '/tabs/settings/device'
      path: '/tabs/settings/device'
      fullPath: '/tabs/settings/device'
      preLoaderRoute: typeof TabsSettingsDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/settings/appearance': {
      id: '/tabs/settings/appearance'
      path: '/tabs/settings/appearance'
      fullPath: '/tabs/settings/appearance'
      preLoaderRoute: typeof TabsSettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/reader/$id': {
      id: '/tabs/reader/$id'
      path: '/tabs/reader/$id'
      fullPath: '/tabs/reader/$id'
      preLoaderRoute: typeof TabsReaderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/library/stats': {
      id: '/tabs/library/stats'
      path: '/tabs/library/stats'
      fullPath: '/tabs/library/stats'
      preLoaderRoute: typeof TabsLibraryStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/explore/web-novels': {
      id: '/tabs/explore/web-novels'
      path: '/tabs/explore/web-novels'
      fullPath: '/tabs/explore/web-novels'
      preLoaderRoute: typeof TabsExploreWebNovelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/explore/web-novel-preview': {
      id: '/tabs/explore/web-novel-preview'
      path: '/tabs/explore/web-novel-preview'
      fullPath: '/tabs/explore/web-novel-preview'
      preLoaderRoute: typeof TabsExploreWebNovelPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/library/series/$id': {
      id: '/tabs/library/series/$id'
      path: '/tabs/library/series/$id'
      fullPath: '/tabs/library/series/$id'
      preLoaderRoute: typeof TabsLibrarySeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/library/book/$id': {
      id: '/tabs/library/book/$id'
      path: '/tabs/library/book/$id'
      fullPath: '/tabs/library/book/$id'
      preLoaderRoute: typeof TabsLibraryBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/explore/book/$catalogId': {
      id: '/tabs/explore/book/$catalogId'
      path: '/tabs/explore/book/$catalogId'
      fullPath: '/tabs/explore/book/$catalogId'
      preLoaderRoute: typeof TabsExploreBookCatalogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  TabsExploreWebNovelPreviewRoute: TabsExploreWebNovelPreviewRoute,
  TabsExploreWebNovelsRoute: TabsExploreWebNovelsRoute,
  TabsLibraryStatsRoute: TabsLibraryStatsRoute,
  TabsReaderIdRoute: TabsReaderIdRoute,
  TabsSettingsAppearanceRoute: TabsSettingsAppearanceRoute,
  TabsSettingsDeviceRoute: TabsSettingsDeviceRoute,
  TabsSettingsExportRoute: TabsSettingsExportRoute,
  TabsSettingsRsvpRoute: TabsSettingsRsvpRoute,
  TabsSettingsSyncRoute: TabsSettingsSyncRoute,
  TabsExploreIndexRoute: TabsExploreIndexRoute,
  TabsLibraryIndexRoute: TabsLibraryIndexRoute,
  TabsSettingsIndexRoute: TabsSettingsIndexRoute,
  TabsExploreBookCatalogIdRoute: TabsExploreBookCatalogIdRoute,
  TabsLibraryBookIdRoute: TabsLibraryBookIdRoute,
  TabsLibrarySeriesIdRoute: TabsLibrarySeriesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
