import {
	FEED_EVENT_TYPES,
	FRIEND_REQUEST_STATES,
	NOTICE_REASONS,
	NOTICE_TARGET_TYPES,
	PROFILE_VISIBILITIES,
	PUSH_PLATFORMS,
} from "@lesefluss/core";
import { sql } from "drizzle-orm";
import {
	type AnyPgColumn,
	boolean,
	check,
	customType,
	index,
	integer,
	jsonb,
	pgTable,
	primaryKey,
	real,
	text,
	timestamp,
	uniqueIndex,
	uuid,
} from "drizzle-orm/pg-core";
import { session, user } from "./auth-schema";

// Better Auth tables live in auth-schema.ts (generated by `pnpx auth@1.6.3 generate`).
// Sync tables are defined below.

/**
 * sync_books - book data keyed by (user_id, book_id).
 * Includes content (plain text), cover image, and chapters for full device restore.
 * Content is immutable per bookId - only pushed once.
 */
export const syncBooks = pgTable(
	"sync_books",
	{
		userId: text("user_id").notNull(),
		bookId: text("book_id").notNull(), // client-generated 8-char hex
		title: text("title").notNull(),
		author: text("author"),
		fileSize: integer("file_size"),
		wordCount: integer("word_count"),
		wordPosition: integer("word_position").notNull().default(0),
		content: text("content"), // full plain text - null until first content push
		coverImage: text("cover_image"), // base64-encoded cover art from EPUB
		chapters: text("chapters"), // JSON: [{title: string, startWord: number}]
		linkRanges: text("link_ranges"), // JSON: [{href: string, startWord: number, endWord: number}]
		source: text("source"), // 'gutenberg' | 'standard_ebooks' | 'url' | 'serial' | null
		catalogId: text("catalog_id"), // e.g. 'gutenberg:1342'
		sourceUrl: text("source_url"), // original URL for source='url' imports
		finishedAt: timestamp("finished_at"), // first crossing of the finished threshold
		// When the book entered the library. Nullable: rows last written by a client
		// that pre-dates the column have none, and a restoring client falls back to
		// the row revision for those.
		addedAt: timestamp("added_at"),
		deleted: boolean("deleted").notNull().default(false), // sticky tombstone
		// Serial/web-novel chapter membership. NULL series_id = standalone book.
		seriesId: text("series_id"),
		chapterIndex: integer("chapter_index"),
		chapterSourceUrl: text("chapter_source_url"),
		chapterStatus: text("chapter_status").notNull().default("fetched"),
		// Reader-editable metadata. `status` null means "derive from progress"
		// (see bookStatus() in @lesefluss/core).
		description: text("description"),
		language: text("language"), // BCP 47 tag
		status: text("status"),
		rating: integer("rating"), // half-stars: 1-10, null = unrated
		review: text("review"),
		tags: text("tags"), // JSON: ["scifi","favorites"]
		// Private to the owner: keeps the book off their social profile and stats.
		// Merged on the metadata revision but outside METADATA_FIELDS; see
		// sync-book-upsert.ts.
		hideFromProfile: boolean("hide_from_profile").notNull().default(false),
		// Which source book this content came from: the row itself for an upload,
		// the first uploader's row for a shared copy. Server-authoritative; a push
		// never sets or changes it (see sync-book-upsert.ts). No FK to user: the
		// origin outlives the uploader's account.
		originUserId: text("origin_user_id").notNull(),
		originBookId: text("origin_book_id").notNull(),
		// Revision of the reading position. Released clients read it as exactly
		// that and adopt the server's position whenever it is higher, so nothing
		// but a position change may move it.
		updatedAt: timestamp("updated_at").notNull(),
		// Revision of the reader-editable fields. Nullable: rows last written by a
		// client that pre-dates the column have none, and the merge falls back to
		// updated_at for those.
		metadataUpdatedAt: timestamp("metadata_updated_at"),
	},
	(t) => [
		primaryKey({ columns: [t.userId, t.bookId] }),
		index("sync_books_origin_idx").on(t.originUserId, t.originBookId),
		// One live copy of an origin per account: a racing second accept links instead of duplicating.
		uniqueIndex("sync_books_user_origin_live_idx")
			.on(t.userId, t.originUserId, t.originBookId)
			.where(sql`NOT ${t.deleted}`),
		check(
			"sync_books_chapter_status_check",
			sql`${t.chapterStatus} IN ('pending', 'fetched', 'locked', 'error')`,
		),
		check(
			"sync_books_status_check",
			sql`${t.status} IS NULL OR ${t.status} IN ('want', 'reading', 'finished', 'dropped')`,
		),
		check("sync_books_rating_check", sql`${t.rating} IS NULL OR ${t.rating} BETWEEN 1 AND 10`),
	],
);

/**
 * sync_series — one row per imported web-novel/serial keyed by (user_id, series_id).
 */
export const syncSeries = pgTable(
	"sync_series",
	{
		userId: text("user_id").notNull(),
		seriesId: text("series_id").notNull(),
		title: text("title").notNull(),
		author: text("author"),
		coverImage: text("cover_image"),
		description: text("description"),
		sourceUrl: text("source_url").notNull(),
		tocUrl: text("toc_url").notNull(),
		provider: text("provider").notNull(),
		lastCheckedAt: timestamp("last_checked_at"),
		createdAt: timestamp("created_at").notNull(),
		deleted: boolean("deleted").notNull().default(false),
		updatedAt: timestamp("updated_at").notNull(),
	},
	(t) => [
		primaryKey({ columns: [t.userId, t.seriesId] }),
		check(
			"sync_series_provider_check",
			sql`${t.provider} IN ('ao3', 'scribblehub', 'royalroad', 'ffnet', 'wuxiaworld', 'rss')`,
		),
	],
);

/**
 * sync_settings - one row per user, mirrors app-relevant settings.
 * Device-only fields (ble_on, inverse, brightness, deep_sleep, etc.) are excluded.
 */
export const syncSettings = pgTable(
	"sync_settings",
	{
		userId: text("user_id").notNull().primaryKey(),
		// RSVP settings
		wpm: integer("wpm").notNull().default(350),
		delayComma: real("delay_comma").notNull().default(2.0),
		delayPeriod: real("delay_period").notNull().default(3.0),
		accelStart: real("accel_start").notNull().default(2.0),
		accelRate: real("accel_rate").notNull().default(0.1),
		xOffset: integer("x_offset").notNull().default(30),
		focalLetterColor: text("focal_letter_color").notNull().default("#ff0000"),
		wordOffset: integer("word_offset").notNull().default(5),
		// Reader appearance
		readerTheme: text("reader_theme").notNull().default("dark"),
		readerFontSize: integer("reader_font_size").notNull().default(16),
		readerFontFamily: text("reader_font_family").notNull().default("sans"),
		readerLineSpacing: real("reader_line_spacing").notNull().default(1.8),
		readerMargin: integer("reader_margin").notNull().default(20),
		showReadingTime: boolean("show_reading_time").notNull().default(true),
		readerActiveWordUnderline: boolean("reader_active_word_underline").notNull().default(true),
		readerGlossaryUnderline: boolean("reader_glossary_underline").notNull().default(true),
		defaultReaderMode: text("default_reader_mode").notNull().default("scroll"),
		paginationStyle: text("pagination_style").notNull().default("scroll"),
		updatedAt: timestamp("updated_at").notNull(),
	},
	(table) => [
		check(
			"sync_settings_default_reader_mode_check",
			sql`${table.defaultReaderMode} IN ('scroll', 'rsvp')`,
		),
		check(
			"sync_settings_focal_letter_color_check",
			sql`${table.focalLetterColor} ~ '^#[0-9A-Fa-f]{6}$'`,
		),
		check(
			"sync_settings_pagination_style_check",
			sql`${table.paginationStyle} IN ('scroll', 'page')`,
		),
	],
);

/**
 * sync_highlights - highlight annotations keyed by (user_id, highlight_id).
 * Uses soft-delete tombstones (deleted=true) so deletions propagate during sync.
 */
export const syncHighlights = pgTable(
	"sync_highlights",
	{
		userId: text("user_id").notNull(),
		highlightId: text("highlight_id").notNull(), // client UUID
		bookId: text("book_id").notNull(),
		startWord: integer("start_word").notNull(),
		startCharInWord: integer("start_char_in_word").notNull().default(0),
		endWord: integer("end_word").notNull(),
		endCharInWord: integer("end_char_in_word").notNull().default(0),
		color: text("color").notNull().default("yellow"), // yellow | blue | orange | pink
		note: text("note"),
		text: text("text"), // extracted text snippet - null for pre-existing highlights
		deleted: boolean("deleted").notNull().default(false),
		createdAt: timestamp("created_at").notNull(),
		updatedAt: timestamp("updated_at").notNull(),
	},
	(t) => [primaryKey({ columns: [t.userId, t.highlightId] })],
);

/**
 * sync_glossary_entries — per-book or global glossary entries.
 * `bookId` is nullable: NULL = global (matches in every book), non-null = book-scoped.
 */
export const syncGlossaryEntries = pgTable(
	"sync_glossary_entries",
	{
		userId: text("user_id").notNull(),
		entryId: text("entry_id").notNull(),
		bookId: text("book_id"), // null = global
		label: text("label").notNull(),
		notes: text("notes"),
		color: text("color").notNull(),
		hideMarker: boolean("hide_marker").notNull().default(false),
		deleted: boolean("deleted").notNull().default(false),
		createdAt: timestamp("created_at").notNull(),
		updatedAt: timestamp("updated_at").notNull(),
	},
	(t) => [primaryKey({ columns: [t.userId, t.entryId] })],
);

/**
 * sync_reading_sessions: one row per in-app reading sitting keyed by (user_id, session_id).
 * Append-only; no soft-delete (sessions are never edited or deleted from the UI).
 * Last-write-wins on `updated_at`.
 */
export const syncReadingSessions = pgTable(
	"sync_reading_sessions",
	{
		userId: text("user_id").notNull(),
		sessionId: text("session_id").notNull(),
		bookId: text("book_id").notNull(),
		mode: text("mode").notNull(), // 'rsvp' | 'scroll' | 'page'
		startedAt: timestamp("started_at").notNull(),
		endedAt: timestamp("ended_at").notNull(),
		durationMs: integer("duration_ms").notNull(),
		wordsRead: integer("words_read").notNull(),
		startWord: integer("start_word").notNull(),
		endWord: integer("end_word").notNull(),
		wpmAvg: integer("wpm_avg"),
		updatedAt: timestamp("updated_at").notNull(),
	},
	(t) => [
		primaryKey({ columns: [t.userId, t.sessionId] }),
		check("sync_reading_sessions_mode_check", sql`${t.mode} IN ('rsvp', 'scroll', 'page')`),
	],
);

export type SyncBook = typeof syncBooks.$inferSelect;
export type NewSyncBook = typeof syncBooks.$inferInsert;
export type SyncSeries = typeof syncSeries.$inferSelect;
export type NewSyncSeries = typeof syncSeries.$inferInsert;
export type SyncSettings = typeof syncSettings.$inferSelect;
export type NewSyncSettings = typeof syncSettings.$inferInsert;
export type SyncHighlight = typeof syncHighlights.$inferSelect;
export type NewSyncHighlight = typeof syncHighlights.$inferInsert;
export type SyncGlossaryEntry = typeof syncGlossaryEntries.$inferSelect;
export type NewSyncGlossaryEntry = typeof syncGlossaryEntries.$inferInsert;
export type SyncReadingSession = typeof syncReadingSessions.$inferSelect;
export type NewSyncReadingSession = typeof syncReadingSessions.$inferInsert;

/**
 * telemetry_events: anonymized diagnostics from clients (no account required).
 * Used to surface silent failures (e.g. position writes that never persist) that
 * never reach us otherwise. Carries no PII: an ephemeral per-launch session id,
 * app version, platform, coarse OS version, and an error message. Append-only.
 */
export const telemetryEvents = pgTable("telemetry_events", {
	id: uuid("id").defaultRandom().primaryKey(),
	type: text("type").notNull(),
	message: text("message"),
	appVersion: text("app_version"),
	platform: text("platform"),
	osVersion: text("os_version"),
	webviewVersion: text("webview_version"),
	sessionId: text("session_id"),
	extra: jsonb("extra"),
	createdAt: timestamp("created_at").notNull().defaultNow(),
});

export type TelemetryEvent = typeof telemetryEvents.$inferSelect;
export type NewTelemetryEvent = typeof telemetryEvents.$inferInsert;

const bytea = customType<{ data: Buffer; driverData: Buffer }>({
	dataType: () => "bytea",
});

/**
 * One row per user who touched their social profile (ADR-0004). A missing row
 * means "no handle, defaults", so nothing is backfilled. `handle` mirrors the
 * active social_handle row for cheap reads. Server-only: none of the social
 * tables ride the sync payload.
 */
export const socialProfile = pgTable(
	"social_profile",
	{
		userId: text("user_id")
			.primaryKey()
			.references(() => user.id, { onDelete: "cascade" }),
		handle: text("handle"),
		handleChangedAt: timestamp("handle_changed_at"),
		bio: text("bio"),
		visibility: text("visibility", { enum: PROFILE_VISIBILITIES }).notNull().default("private"),
		showCurrentlyReading: boolean("show_currently_reading").notNull().default(true),
		showFinished: boolean("show_finished").notNull().default(true),
		showStats: boolean("show_stats").notNull().default(true),
		showHighlights: boolean("show_highlights").notNull().default(true),
		feedEnabled: boolean("feed_enabled").notNull().default(true),
		shareLiveReading: boolean("share_live_reading").notNull().default(true),
		/** The owner's IANA zone, for their own dates and "this year" stats; never shown to others. */
		timeZone: text("time_zone"),
		updatedAt: timestamp("updated_at").notNull().defaultNow(),
	},
	(t) => [check("social_profile_visibility_check", sql`${t.visibility} IN ('private', 'friends')`)],
);

/**
 * One row per started or finished book, referencing the actor's own
 * `sync_books` row: title, cover and rating are joined at read time, so a
 * deleted, hidden or taken-down book drops out of every feed on its own.
 */
export const socialFeedEvent = pgTable(
	"social_feed_event",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		actorId: text("actor_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		bookId: text("book_id").notNull(),
		type: text("type", { enum: FEED_EVENT_TYPES }).notNull(),
		createdAt: timestamp("created_at").notNull().defaultNow(),
		payload: jsonb("payload"),
	},
	(t) => [
		uniqueIndex("social_feed_event_book_type_idx").on(t.actorId, t.bookId, t.type),
		index("social_feed_event_actor_created_idx").on(t.actorId, t.createdAt, t.id),
		index("social_feed_event_created_idx").on(t.createdAt),
		check("social_feed_event_type_check", sql`${t.type} IN ('started', 'finished')`),
	],
);

/**
 * Every handle ever claimed, keyed by its normalised form: the primary key is
 * the uniqueness guarantee. Active while `released_at` is null. A released row
 * blocks the handle for HANDLE_RELEASE_HOLD_DAYS; the previous owner may take
 * it back meanwhile unless `reclaimable` is false (admin reset). `user_id` is
 * nulled by the FK when the account goes, so the hold outlives the account
 * without pointing at it.
 */
export const socialHandle = pgTable(
	"social_handle",
	{
		handle: text("handle").primaryKey(),
		userId: text("user_id").references(() => user.id, { onDelete: "set null" }),
		claimedAt: timestamp("claimed_at").notNull().defaultNow(),
		releasedAt: timestamp("released_at"),
		reclaimable: boolean("reclaimable").notNull().default(true),
	},
	(t) => [index("social_handle_user_id_idx").on(t.userId)],
);

/**
 * The stored 256px WebP avatar. `id` is the only thing in the public URL:
 * an <img> cannot carry a bearer token, so the random id is the access
 * control, and replacing the image mints a new id so cached URLs go stale.
 */
export const socialAvatar = pgTable("social_avatar", {
	id: uuid("id").defaultRandom().primaryKey(),
	userId: text("user_id")
		.notNull()
		.unique()
		.references(() => user.id, { onDelete: "cascade" }),
	data: bytea("data").notNull(),
	createdAt: timestamp("created_at").notNull().defaultNow(),
});

export type SocialHandle = typeof socialHandle.$inferSelect;

/** One row per unordered pair, stored ordered so the PK is the "are friends" lookup. */
export const socialFriendship = pgTable(
	"social_friendship",
	{
		userLow: text("user_low")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		userHigh: text("user_high")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		acceptedAt: timestamp("accepted_at").notNull().defaultNow(),
	},
	(t) => [
		primaryKey({ columns: [t.userLow, t.userHigh] }),
		index("social_friendship_user_high_idx").on(t.userHigh),
		check("social_friendship_order_check", sql`${t.userLow} < ${t.userHigh}`),
	],
);

/**
 * One row per direction. Expiry is derived from `created_at`. A declined row
 * stays for the decline cooldown, and a re-request inside it only bumps
 * `created_at`, so the sender keeps seeing "pending" while the addressee sees
 * nothing.
 */
export const socialFriendRequest = pgTable(
	"social_friend_request",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		requesterId: text("requester_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		addresseeId: text("addressee_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		state: text("state", { enum: FRIEND_REQUEST_STATES }).notNull().default("pending"),
		createdAt: timestamp("created_at").notNull().defaultNow(),
		resolvedAt: timestamp("resolved_at"),
	},
	(t) => [
		uniqueIndex("social_friend_request_pair_idx").on(t.requesterId, t.addresseeId),
		index("social_friend_request_addressee_idx").on(t.addresseeId),
		check("social_friend_request_self_check", sql`${t.requesterId} <> ${t.addresseeId}`),
	],
);

export const socialBlock = pgTable(
	"social_block",
	{
		blockerId: text("blocker_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		blockedId: text("blocked_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		createdAt: timestamp("created_at").notNull().defaultNow(),
	},
	(t) => [
		primaryKey({ columns: [t.blockerId, t.blockedId] }),
		index("social_block_blocked_idx").on(t.blockedId),
	],
);

/**
 * One row per owner: "at most one active invite link" is structural. The
 * token is stored as is (256 random bits) because the owner must be able to
 * copy the current link again.
 */
export const socialInvite = pgTable("social_invite", {
	ownerId: text("owner_id")
		.primaryKey()
		.references(() => user.id, { onDelete: "cascade" }),
	token: text("token").notNull().unique(),
	createdAt: timestamp("created_at").notNull().defaultNow(),
	expiresAt: timestamp("expires_at").notNull(),
	revokedAt: timestamp("revoked_at"),
});

export type SocialFriendRequest = typeof socialFriendRequest.$inferSelect;

/**
 * One inbox item. The unique key collapses a repeated event into the same row
 * (and id) instead of stacking. `subject_id` is '' for types without a subject
 * because the unique index must treat "no subject" as one value.
 */
// Rows without an actor (moderation items) never collapse: NULLs are distinct
// in the event index, so each such item needs a subject id of its own.
export const socialNotification = pgTable(
	"social_notification",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		recipientId: text("recipient_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		/** Null when Lesefluss itself is the sender (moderation items). */
		actorId: text("actor_id").references(() => user.id, { onDelete: "cascade" }),
		type: text("type").notNull(),
		subjectId: text("subject_id").notNull().default(""),
		payload: jsonb("payload").$type<{ text: string }>(),
		createdAt: timestamp("created_at").notNull().defaultNow(),
		readAt: timestamp("read_at"),
	},
	(t) => [
		uniqueIndex("social_notification_event_idx").on(t.recipientId, t.type, t.actorId, t.subjectId),
		index("social_notification_recipient_created_idx").on(t.recipientId, t.createdAt),
		index("social_notification_unread_idx").on(t.recipientId).where(sql`${t.readAt} IS NULL`),
	],
);

export type SocialNotification = typeof socialNotification.$inferSelect;

/**
 * One row per device that may receive push. Bound to the session that
 * registered it, so signing out, revoking or banning drops the device too.
 */
export const socialPushToken = pgTable(
	"social_push_token",
	{
		token: text("token").primaryKey(),
		platform: text("platform", { enum: PUSH_PLATFORMS }).notNull(),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		sessionId: text("session_id")
			.notNull()
			.references(() => session.id, { onDelete: "cascade" }),
		createdAt: timestamp("created_at").notNull().defaultNow(),
		updatedAt: timestamp("updated_at").notNull().defaultNow(),
	},
	(t) => [
		index("social_push_token_user_idx").on(t.userId),
		check("social_push_token_platform_check", sql`${t.platform} IN ('android', 'ios')`),
	],
);

/** Server-only, never in `sync_settings`: older builds push that row whole. A missing row means all on. */
export const socialPushPreferences = pgTable("social_push_preferences", {
	userId: text("user_id")
		.primaryKey()
		.references(() => user.id, { onDelete: "cascade" }),
	friendRequests: boolean("friend_requests").notNull().default(true),
	shares: boolean("shares").notNull().default(true),
	buddyReads: boolean("buddy_reads").notNull().default(true),
	discussion: boolean("discussion").notNull().default(true),
	previews: boolean("previews").notNull().default(true),
	updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

/**
 * Pushes waiting to be sent. A row names its inbox event, not its text, which
 * is rendered and re-checked at send time. Events that share a `dedupe_key`
 * merge into one row, which is how bursts collapse into one push.
 */
export const socialPushOutbox = pgTable(
	"social_push_outbox",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		dedupeKey: text("dedupe_key").notNull().unique(),
		recipientId: text("recipient_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		actorId: text("actor_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		type: text("type").notNull(),
		subjectId: text("subject_id").notNull(),
		createdAt: timestamp("created_at").notNull().defaultNow(),
		sendAfter: timestamp("send_after").notNull(),
	},
	(t) => [index("social_push_outbox_send_after_idx").on(t.sendAfter)],
);

export type SocialPushOutboxRow = typeof socialPushOutbox.$inferSelect;

/** Sends of the last hour, for the rate caps; older rows are swept. */
export const socialPushSent = pgTable(
	"social_push_sent",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		recipientId: text("recipient_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		actorId: text("actor_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		sentAt: timestamp("sent_at").notNull().defaultNow(),
	},
	(t) => [index("social_push_sent_recipient_idx").on(t.recipientId, t.sentAt)],
);

export const NOTICE_STATUSES = ["open", "actioned", "rejected"] as const;
export type NoticeStatus = (typeof NOTICE_STATUSES)[number];
export const NOTICE_SOURCES = ["app", "web"] as const;

type MailDelivery = { status: "sent" | "failed" | "skipped"; error?: string; at: number };
export type NoticeMailState = {
	/** `text` is the statement as sent, so a resend repeats the decision verbatim. */
	statement?: MailDelivery & { text?: string };
	notifier?: MailDelivery;
};

/**
 * A DSA Art. 16 notice. No FK to `user`: notices outlive both the notifier's
 * and the reported user's account for their retention period, with the
 * notifier's identity nulled on deletion.
 */
export const socialNotice = pgTable(
	"social_notice",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		status: text("status", { enum: NOTICE_STATUSES }).notNull().default("open"),
		targetType: text("target_type", { enum: NOTICE_TARGET_TYPES }).notNull(),
		/** How the notifier located it: a handle, or "userId:bookId"; unresolved web input stays as typed. */
		targetRef: text("target_ref").notNull(),
		targetUserId: text("target_user_id"),
		targetSnapshot: jsonb("target_snapshot").$type<Record<string, string | null>>(),
		reason: text("reason", { enum: NOTICE_REASONS }).notNull(),
		text: text("text").notNull(),
		source: text("source", { enum: NOTICE_SOURCES }).notNull(),
		notifierUserId: text("notifier_user_id"),
		notifierName: text("notifier_name"),
		notifierEmail: text("notifier_email"),
		createdAt: timestamp("created_at").notNull().defaultNow(),
		decidedAt: timestamp("decided_at"),
		decidedBy: text("decided_by"),
		decision: text("decision"),
		decisionNote: text("decision_note"),
		mailState: jsonb("mail_state").$type<NoticeMailState>().notNull().default({}),
	},
	(t) => [
		index("social_notice_status_created_idx").on(t.status, t.createdAt),
		index("social_notice_target_decided_idx").on(t.targetUserId, t.decidedAt),
	],
);
export type SocialNotice = typeof socialNotice.$inferSelect;

export const RESTRICTION_KINDS = ["sharing_suspended"] as const;

/** A restriction we imposed; `until` null is permanent, `liftedAt` set means over. */
export const socialRestriction = pgTable(
	"social_restriction",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		userId: text("user_id").notNull(),
		kind: text("kind", { enum: RESTRICTION_KINDS }).notNull(),
		until: timestamp("until"),
		reason: text("reason").notNull(),
		noticeId: uuid("notice_id"),
		/** Admin user id, or "auto" for the repeat-offender rule. */
		createdBy: text("created_by").notNull(),
		createdAt: timestamp("created_at").notNull().defaultNow(),
		liftedAt: timestamp("lifted_at"),
		liftedBy: text("lifted_by"),
	},
	(t) => [index("social_restriction_user_kind_idx").on(t.userId, t.kind)],
);
export type SocialRestriction = typeof socialRestriction.$inferSelect;

export const TAKEDOWN_SCOPES = ["copy", "origin"] as const;

/** Removal record: the sync push refuses to recreate a listed (user, book) even after its tombstone is gone. */
export const socialTakedown = pgTable(
	"social_takedown",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		scope: text("scope", { enum: TAKEDOWN_SCOPES }).notNull(),
		userId: text("user_id").notNull(),
		bookId: text("book_id").notNull(),
		originUserId: text("origin_user_id"),
		originBookId: text("origin_book_id"),
		noticeId: uuid("notice_id"),
		createdAt: timestamp("created_at").notNull().defaultNow(),
	},
	(t) => [
		uniqueIndex("social_takedown_book_idx").on(t.userId, t.bookId),
		index("social_takedown_origin_idx").on(t.originUserId, t.originBookId),
	],
);
export type SocialTakedown = typeof socialTakedown.$inferSelect;

export const COPY_SOURCES = ["share", "buddy_read"] as const;

/**
 * Every server-made copy. Clear cloud data leaves it alone, so a copy that is
 * pushed back after a purge gets its recorded origin instead of its own ids.
 */
export const syncBookCopy = pgTable(
	"sync_book_copy",
	{
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		bookId: text("book_id").notNull(),
		originUserId: text("origin_user_id").notNull(),
		originBookId: text("origin_book_id").notNull(),
		via: text("via", { enum: COPY_SOURCES }).notNull(),
		createdAt: timestamp("created_at").notNull().defaultNow(),
	},
	(t) => [primaryKey({ columns: [t.userId, t.bookId] })],
);

export const SHARE_STATUSES = ["pending", "accepted", "declined", "expired", "revoked"] as const;
export type ShareStatus = (typeof SHARE_STATUSES)[number];

export const socialShare = pgTable(
	"social_share",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		senderId: text("sender_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		recipientId: text("recipient_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		/** The sender's row; the copy is made from it at accept time. */
		bookId: text("book_id").notNull(),
		originUserId: text("origin_user_id").notNull(),
		originBookId: text("origin_book_id").notNull(),
		/** What the recipient is offered, as it was when shared; the source may change or vanish. */
		title: text("title").notNull(),
		author: text("author"),
		wordCount: integer("word_count"),
		status: text("status", { enum: SHARE_STATUSES }).notNull().default("pending"),
		/** The recipient's book after accept, new or linked. */
		copyBookId: text("copy_book_id"),
		createdAt: timestamp("created_at").notNull().defaultNow(),
		resolvedAt: timestamp("resolved_at"),
	},
	(t) => [
		index("social_share_recipient_status_idx").on(t.recipientId, t.status),
		index("social_share_sender_created_idx").on(t.senderId, t.createdAt),
		uniqueIndex("social_share_pending_idx")
			.on(t.senderId, t.recipientId, t.originUserId, t.originBookId)
			.where(sql`${t.status} = 'pending'`),
	],
);
export type SocialShare = typeof socialShare.$inferSelect;

/** The one-time confirmation that the user shares only what they may. */
export const socialShareConsent = pgTable("social_share_consent", {
	userId: text("user_id")
		.primaryKey()
		.references(() => user.id, { onDelete: "cascade" }),
	confirmedAt: timestamp("confirmed_at").notNull().defaultNow(),
});

export const BUDDY_READ_STATUSES = ["in_progress", "finished"] as const;
export const BUDDY_READ_MEMBER_STATES = ["active", "left", "removed"] as const;
export const BUDDY_READ_INVITE_STATUSES = ["pending", "accepted", "declined", "cancelled"] as const;

/**
 * A group reading one content origin. `host_id` is who created it; the
 * effective host is derived (this user while a current member, else the
 * earliest-joined current member), so account deletion needs no handover.
 */
export const buddyRead = pgTable(
	"buddy_read",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		originUserId: text("origin_user_id").notNull(),
		originBookId: text("origin_book_id").notNull(),
		hostId: text("host_id").references(() => user.id, { onDelete: "set null" }),
		title: text("title").notNull(),
		author: text("author"),
		status: text("status", { enum: BUDDY_READ_STATUSES }).notNull().default("in_progress"),
		targetDate: timestamp("target_date"),
		createdAt: timestamp("created_at").notNull().defaultNow(),
		finishedAt: timestamp("finished_at"),
	},
	(t) => [index("buddy_read_origin_idx").on(t.originUserId, t.originBookId)],
);
export type BuddyRead = typeof buddyRead.$inferSelect;

/** One row per person who ever joined; `book_id` is their own linked `sync_books` row. */
export const buddyReadMember = pgTable(
	"buddy_read_member",
	{
		buddyReadId: uuid("buddy_read_id")
			.notNull()
			.references(() => buddyRead.id, { onDelete: "cascade" }),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		bookId: text("book_id").notNull(),
		state: text("state", { enum: BUDDY_READ_MEMBER_STATES }).notNull().default("active"),
		joinedAt: timestamp("joined_at").notNull().defaultNow(),
		leftAt: timestamp("left_at"),
		/**
		 * Set once the member's position has been seen below the finished
		 * threshold since joining; only then does reaching it count, so a book
		 * finished before joining does not finish the member.
		 */
		finishArmed: boolean("finish_armed").notNull().default(false),
		finishedAt: timestamp("finished_at"),
		/** Only ever raised: what the member has unlocked in the discussion stays unlocked. */
		furthestWord: integer("furthest_word").notNull().default(0),
		shareAllHighlights: boolean("share_all_highlights").notNull().default(false),
		showEverything: boolean("show_everything").notNull().default(false),
	},
	(t) => [
		primaryKey({ columns: [t.buddyReadId, t.userId] }),
		index("buddy_read_member_user_idx").on(t.userId),
	],
);
export type BuddyReadMember = typeof buddyReadMember.$inferSelect;

export const buddyReadInvite = pgTable(
	"buddy_read_invite",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		buddyReadId: uuid("buddy_read_id")
			.notNull()
			.references(() => buddyRead.id, { onDelete: "cascade" }),
		inviterId: text("inviter_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		inviteeId: text("invitee_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		status: text("status", { enum: BUDDY_READ_INVITE_STATUSES }).notNull().default("pending"),
		createdAt: timestamp("created_at").notNull().defaultNow(),
		resolvedAt: timestamp("resolved_at"),
	},
	(t) => [
		index("buddy_read_invite_invitee_idx").on(t.inviteeId, t.status),
		uniqueIndex("buddy_read_invite_pending_idx")
			.on(t.buddyReadId, t.inviteeId)
			.where(sql`${t.status} = 'pending'`),
	],
);
export type BuddyReadInvite = typeof buddyReadInvite.$inferSelect;

export const DISCUSSION_ANCHOR_KINDS = ["range", "chapter"] as const;

/** A comment in a buddy read. Replies copy their parent's anchor, so gating never needs the parent. */
export const buddyReadComment = pgTable(
	"buddy_read_comment",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		buddyReadId: uuid("buddy_read_id")
			.notNull()
			.references(() => buddyRead.id, { onDelete: "cascade" }),
		kind: text("kind").notNull().default("comment"),
		authorId: text("author_id").references(() => user.id, { onDelete: "set null" }),
		parentId: uuid("parent_id").references((): AnyPgColumn => buddyReadComment.id, {
			onDelete: "cascade",
		}),
		anchorKind: text("anchor_kind", { enum: DISCUSSION_ANCHOR_KINDS }).notNull(),
		startWord: integer("start_word").notNull(),
		startCharInWord: integer("start_char_in_word").notNull().default(0),
		endWord: integer("end_word").notNull(),
		endCharInWord: integer("end_char_in_word").notNull().default(0),
		/** Null once removed by its author (with replies left) or by a takedown. */
		body: text("body"),
		createdAt: timestamp("created_at").notNull().defaultNow(),
		editedAt: timestamp("edited_at"),
		deletedAt: timestamp("deleted_at"),
	},
	(t) => [
		index("buddy_read_comment_read_idx").on(t.buddyReadId, t.startWord),
		index("buddy_read_comment_author_idx").on(t.authorId),
		index("buddy_read_comment_parent_idx").on(t.parentId),
	],
);
export type BuddyReadComment = typeof buddyReadComment.$inferSelect;

/**
 * A highlight shared into a buddy read: a reference to the author's own
 * `sync_highlights` row, read through at display time so highlight sync keeps
 * it current. `removed_at` marks a takedown, which also bars re-sharing.
 */
export const buddyReadSharedHighlight = pgTable(
	"buddy_read_shared_highlight",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		buddyReadId: uuid("buddy_read_id")
			.notNull()
			.references(() => buddyRead.id, { onDelete: "cascade" }),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		highlightId: text("highlight_id").notNull(),
		/** False for a reference created only because share-all was on. */
		sharedIndividually: boolean("shared_individually").notNull().default(true),
		createdAt: timestamp("created_at").notNull().defaultNow(),
		removedAt: timestamp("removed_at"),
	},
	(t) => [
		uniqueIndex("buddy_read_shared_highlight_idx").on(t.buddyReadId, t.userId, t.highlightId),
	],
);
export type BuddyReadSharedHighlight = typeof buddyReadSharedHighlight.$inferSelect;

export const buddyReadReaction = pgTable(
	"buddy_read_reaction",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		buddyReadId: uuid("buddy_read_id")
			.notNull()
			.references(() => buddyRead.id, { onDelete: "cascade" }),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		commentId: uuid("comment_id").references(() => buddyReadComment.id, { onDelete: "cascade" }),
		sharedHighlightId: uuid("shared_highlight_id").references(() => buddyReadSharedHighlight.id, {
			onDelete: "cascade",
		}),
		emoji: text("emoji").notNull(),
		createdAt: timestamp("created_at").notNull().defaultNow(),
	},
	(t) => [
		uniqueIndex("buddy_read_reaction_comment_idx")
			.on(t.commentId, t.userId, t.emoji)
			.where(sql`${t.commentId} IS NOT NULL`),
		uniqueIndex("buddy_read_reaction_highlight_idx")
			.on(t.sharedHighlightId, t.userId, t.emoji)
			.where(sql`${t.sharedHighlightId} IS NOT NULL`),
		check(
			"buddy_read_reaction_one_target",
			sql`(${t.commentId} IS NULL) <> (${t.sharedHighlightId} IS NULL)`,
		),
	],
);
