import { sql } from "drizzle-orm";
import {
	boolean,
	check,
	integer,
	pgTable,
	primaryKey,
	real,
	text,
	timestamp,
} from "drizzle-orm/pg-core";

// Better Auth tables live in auth-schema.ts (generated by `pnpx auth@1.6.3 generate`).
// Sync tables are defined below.

/**
 * sync_books - book data keyed by (user_id, book_id).
 * Includes content (plain text), cover image, and chapters for full device restore.
 * Content is immutable per bookId - only pushed once.
 */
export const syncBooks = pgTable(
	"sync_books",
	{
		userId: text("user_id").notNull(),
		bookId: text("book_id").notNull(), // client-generated 8-char hex
		title: text("title").notNull(),
		author: text("author"),
		fileSize: integer("file_size"),
		wordCount: integer("word_count"),
		position: integer("position").notNull().default(0), // byte offset
		content: text("content"), // full plain text - null until first content push
		coverImage: text("cover_image"), // base64-encoded cover art from EPUB
		chapters: text("chapters"), // JSON: [{title: string, startByte: number}]
		source: text("source"), // 'gutenberg' | 'standard_ebooks' | 'url' | 'serial' | null
		catalogId: text("catalog_id"), // e.g. 'gutenberg:1342'
		sourceUrl: text("source_url"), // original URL for source='url' imports
		deleted: boolean("deleted").notNull().default(false), // sticky tombstone
		// Serial/web-novel chapter membership. NULL series_id = standalone book.
		seriesId: text("series_id"),
		chapterIndex: integer("chapter_index"),
		chapterSourceUrl: text("chapter_source_url"),
		chapterStatus: text("chapter_status").notNull().default("fetched"),
		updatedAt: timestamp("updated_at").notNull(),
	},
	(t) => [
		primaryKey({ columns: [t.userId, t.bookId] }),
		check(
			"sync_books_chapter_status_check",
			sql`${t.chapterStatus} IN ('pending', 'fetched', 'locked', 'error')`,
		),
	],
);

/**
 * sync_series — one row per imported web-novel/serial keyed by (user_id, series_id).
 */
export const syncSeries = pgTable(
	"sync_series",
	{
		userId: text("user_id").notNull(),
		seriesId: text("series_id").notNull(),
		title: text("title").notNull(),
		author: text("author"),
		coverImage: text("cover_image"),
		description: text("description"),
		sourceUrl: text("source_url").notNull(),
		tocUrl: text("toc_url").notNull(),
		provider: text("provider").notNull(),
		lastCheckedAt: timestamp("last_checked_at"),
		createdAt: timestamp("created_at").notNull(),
		deleted: boolean("deleted").notNull().default(false),
		updatedAt: timestamp("updated_at").notNull(),
	},
	(t) => [
		primaryKey({ columns: [t.userId, t.seriesId] }),
		check(
			"sync_series_provider_check",
			sql`${t.provider} IN ('ao3', 'scribblehub', 'royalroad', 'ffnet', 'wuxiaworld', 'rss')`,
		),
	],
);

/**
 * sync_settings - one row per user, mirrors app-relevant settings.
 * Device-only fields (ble_on, inverse, brightness, deep_sleep, etc.) are excluded.
 */
export const syncSettings = pgTable(
	"sync_settings",
	{
		userId: text("user_id").notNull().primaryKey(),
		// RSVP settings
		wpm: integer("wpm").notNull().default(350),
		delayComma: real("delay_comma").notNull().default(2.0),
		delayPeriod: real("delay_period").notNull().default(3.0),
		accelStart: real("accel_start").notNull().default(2.0),
		accelRate: real("accel_rate").notNull().default(0.1),
		xOffset: integer("x_offset").notNull().default(30),
		wordOffset: integer("word_offset").notNull().default(5),
		// Reader appearance
		readerTheme: text("reader_theme").notNull().default("dark"),
		readerFontSize: integer("reader_font_size").notNull().default(16),
		readerFontFamily: text("reader_font_family").notNull().default("sans"),
		readerLineSpacing: real("reader_line_spacing").notNull().default(1.8),
		readerMargin: integer("reader_margin").notNull().default(20),
		showReadingTime: boolean("show_reading_time").notNull().default(true),
		readerActiveWordUnderline: boolean("reader_active_word_underline").notNull().default(true),
		readerGlossaryUnderline: boolean("reader_glossary_underline").notNull().default(true),
		defaultReaderMode: text("default_reader_mode").notNull().default("scroll"),
		paginationStyle: text("pagination_style").notNull().default("scroll"),
		updatedAt: timestamp("updated_at").notNull(),
	},
	(table) => [
		check(
			"sync_settings_default_reader_mode_check",
			sql`${table.defaultReaderMode} IN ('scroll', 'rsvp')`,
		),
		check(
			"sync_settings_pagination_style_check",
			sql`${table.paginationStyle} IN ('scroll', 'page')`,
		),
	],
);

/**
 * sync_highlights - highlight annotations keyed by (user_id, highlight_id).
 * Uses soft-delete tombstones (deleted=true) so deletions propagate during sync.
 */
export const syncHighlights = pgTable(
	"sync_highlights",
	{
		userId: text("user_id").notNull(),
		highlightId: text("highlight_id").notNull(), // client UUID
		bookId: text("book_id").notNull(),
		startOffset: integer("start_offset").notNull(), // UTF-8 byte offset
		endOffset: integer("end_offset").notNull(),
		color: text("color").notNull().default("yellow"), // yellow | blue | orange | pink
		note: text("note"),
		text: text("text"), // extracted text snippet - null for pre-existing highlights
		deleted: boolean("deleted").notNull().default(false),
		createdAt: timestamp("created_at").notNull(),
		updatedAt: timestamp("updated_at").notNull(),
	},
	(t) => [primaryKey({ columns: [t.userId, t.highlightId] })],
);

/**
 * sync_glossary_entries — per-book or global glossary entries.
 * `bookId` is nullable: NULL = global (matches in every book), non-null = book-scoped.
 */
export const syncGlossaryEntries = pgTable(
	"sync_glossary_entries",
	{
		userId: text("user_id").notNull(),
		entryId: text("entry_id").notNull(),
		bookId: text("book_id"), // null = global
		label: text("label").notNull(),
		notes: text("notes"),
		color: text("color").notNull(),
		hideMarker: boolean("hide_marker").notNull().default(false),
		deleted: boolean("deleted").notNull().default(false),
		createdAt: timestamp("created_at").notNull(),
		updatedAt: timestamp("updated_at").notNull(),
	},
	(t) => [primaryKey({ columns: [t.userId, t.entryId] })],
);

export type SyncBook = typeof syncBooks.$inferSelect;
export type NewSyncBook = typeof syncBooks.$inferInsert;
export type SyncSeries = typeof syncSeries.$inferSelect;
export type NewSyncSeries = typeof syncSeries.$inferInsert;
export type SyncSettings = typeof syncSettings.$inferSelect;
export type NewSyncSettings = typeof syncSettings.$inferInsert;
export type SyncHighlight = typeof syncHighlights.$inferSelect;
export type NewSyncHighlight = typeof syncHighlights.$inferInsert;
export type SyncGlossaryEntry = typeof syncGlossaryEntries.$inferSelect;
export type NewSyncGlossaryEntry = typeof syncGlossaryEntries.$inferInsert;
