import { sql } from "drizzle-orm";
import {
	boolean,
	check,
	integer,
	pgTable,
	primaryKey,
	real,
	text,
	timestamp,
} from "drizzle-orm/pg-core";

// Better Auth tables live in auth-schema.ts (generated by `pnpx auth@1.6.3 generate`).
// Sync tables are defined below.

/**
 * sync_books - book data keyed by (user_id, book_id).
 * Includes content (plain text), cover image, and chapters for full device restore.
 * Content is immutable per bookId - only pushed once.
 */
export const syncBooks = pgTable(
	"sync_books",
	{
		userId: text("user_id").notNull(),
		bookId: text("book_id").notNull(), // client-generated 8-char hex
		title: text("title").notNull(),
		author: text("author"),
		fileSize: integer("file_size"),
		wordCount: integer("word_count"),
		position: integer("position").notNull().default(0), // byte offset
		content: text("content"), // full plain text - null until first content push
		coverImage: text("cover_image"), // base64-encoded cover art from EPUB
		chapters: text("chapters"), // JSON: [{title: string, startByte: number}]
		source: text("source"), // 'gutenberg' | 'standard_ebooks' | null (null = local import)
		catalogId: text("catalog_id"), // e.g. 'gutenberg:1342'
		updatedAt: timestamp("updated_at").notNull(),
	},
	(t) => [primaryKey({ columns: [t.userId, t.bookId] })],
);

/**
 * sync_settings - one row per user, mirrors app-relevant settings.
 * Device-only fields (ble_on, inverse, brightness, deep_sleep, etc.) are excluded.
 */
export const syncSettings = pgTable(
	"sync_settings",
	{
		userId: text("user_id").notNull().primaryKey(),
		// RSVP settings
		wpm: integer("wpm").notNull().default(350),
		delayComma: real("delay_comma").notNull().default(2.0),
		delayPeriod: real("delay_period").notNull().default(3.0),
		accelStart: real("accel_start").notNull().default(2.0),
		accelRate: real("accel_rate").notNull().default(0.1),
		xOffset: integer("x_offset").notNull().default(30),
		wordOffset: integer("word_offset").notNull().default(5),
		// Reader appearance
		readerTheme: text("reader_theme").notNull().default("dark"),
		readerFontSize: integer("reader_font_size").notNull().default(16),
		readerFontFamily: text("reader_font_family").notNull().default("sans"),
		readerLineSpacing: real("reader_line_spacing").notNull().default(1.8),
		readerMargin: integer("reader_margin").notNull().default(20),
		showReadingTime: boolean("show_reading_time").notNull().default(true),
		haptics: boolean("haptics").notNull().default(false),
		defaultReaderMode: text("default_reader_mode").notNull().default("scroll"),
		updatedAt: timestamp("updated_at").notNull(),
	},
	(table) => [
		check("sync_settings_default_reader_mode_check", sql`${table.defaultReaderMode} IN ('scroll', 'rsvp')`),
	],
);

/**
 * sync_highlights - highlight annotations keyed by (user_id, highlight_id).
 * Uses soft-delete tombstones (deleted=true) so deletions propagate during sync.
 */
export const syncHighlights = pgTable(
	"sync_highlights",
	{
		userId: text("user_id").notNull(),
		highlightId: text("highlight_id").notNull(), // client UUID
		bookId: text("book_id").notNull(),
		startOffset: integer("start_offset").notNull(), // UTF-8 byte offset
		endOffset: integer("end_offset").notNull(),
		color: text("color").notNull().default("yellow"), // yellow | blue | orange | pink
		note: text("note"),
		text: text("text"), // extracted text snippet - null for pre-existing highlights
		deleted: boolean("deleted").notNull().default(false),
		createdAt: timestamp("created_at").notNull(),
		updatedAt: timestamp("updated_at").notNull(),
	},
	(t) => [primaryKey({ columns: [t.userId, t.highlightId] })],
);

export type SyncBook = typeof syncBooks.$inferSelect;
export type NewSyncBook = typeof syncBooks.$inferInsert;
export type SyncSettings = typeof syncSettings.$inferSelect;
export type NewSyncSettings = typeof syncSettings.$inferInsert;
export type SyncHighlight = typeof syncHighlights.$inferSelect;
export type NewSyncHighlight = typeof syncHighlights.$inferInsert;
